<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $languages = [
                ["title"=>"Abkhaz","description"=>"аҧсуа"],
                ["title"=>"Afar","description"=>"Afaraf"],
                ["title"=>"Afrikaans","description"=>"Afrikaans"],
                ["title"=>"Akan","description"=>"Akan"],
                ["title"=>"Albanian","description"=>"Shqip"],
                ["title"=>"Amharic","description"=>"አማርኛ"],
                ["title"=>"Arabic","description"=>"العربية"],
                ["title"=>"Aragonese","description"=>"Aragonés"],
                ["title"=>"Armenian","description"=>"Հայերեն"],
                ["title"=>"Assamese","description"=>"অসমীয়া"],
                ["title"=>"Avaric","description"=>"авар мацӀ, магӀарул мацӀ"],
                ["title"=>"Avestan","description"=>"avesta"],
                ["title"=>"Aymara","description"=>"aymar aru"],
                ["title"=>"Azerbaijani","description"=>"azərbaycan dili"],
                ["title"=>"Bambara","description"=>"bamanankan"],
                ["title"=>"Bashkir","description"=>"башҡорт теле"],
                ["title"=>"Basque","description"=>"euskara, euskera"],
                ["title"=>"Belarusian","description"=>"Беларуская"],
                ["title"=>"Bengali","description"=>"বাংলা"],
                ["title"=>"Bihari","description"=>"भोजपुरी"],
                ["title"=>"Bislama","description"=>"Bislama"],
                ["title"=>"Bosnian","description"=>"bosanski jezik"],
                ["title"=>"Breton","description"=>"brezhoneg"],
                ["title"=>"Bulgarian","description"=>"български език"],
                ["title"=>"Burmese","description"=>"ဗမာစာ"],
                ["title"=>"Catalan; Valencian","description"=>"Català"],
                ["title"=>"Chamorro","description"=>"Chamoru"],
                ["title"=>"Chechen","description"=>"нохчийн мотт"],
                ["title"=>"Chichewa; Chewa; Nyanja","description"=>"chiCheŵa, chinyanja"],
                ["title"=>"Chinese","description"=>"中文 (Zhōngwén), 汉语, 漢語"],
                ["title"=>"Chuvash","description"=>"чӑваш чӗлхи"],
                ["title"=>"Cornish","description"=>"Kernewek"],
                ["title"=>"Corsican","description"=>"corsu, lingua corsa"],
                ["title"=>"Cree","description"=>"ᓀᐦᐃᔭᐍᐏᐣ"],
                ["title"=>"Croatian","description"=>"hrvatski"],
                ["title"=>"Czech","description"=>"česky, čeština"],
                ["title"=>"Danish","description"=>"dansk"],
                ["title"=>"Divehi; Dhivehi; Maldivian;","description"=>"ދިވެހި"],
                ["title"=>"Dutch","description"=>"Nederlands, Vlaams"],
                ["title"=>"English","description"=>"English"],
                ["title"=>"Esperanto","description"=>"Esperanto"],
                ["title"=>"Estonian","description"=>"eesti, eesti keel"],
                ["title"=>"Ewe","description"=>"Eʋegbe"],
                ["title"=>"Faroese","description"=>"føroyskt"],
                ["title"=>"Fijian","description"=>"vosa Vakaviti"],
                ["title"=>"Finnish","description"=>"suomi, suomen kieli"],
                ["title"=>"French","description"=>"français, langue française"],
                ["title"=>"Fula; Fulah; Pulaar; Pular","description"=>"Fulfulde, Pulaar, Pular"],
                ["title"=>"Galician","description"=>"Galego"],
                ["title"=>"Georgian","description"=>"ქართული"],
                ["title"=>"German","description"=>"Deutsch"],
                ["title"=>"Greek, Modern","description"=>"Ελληνικά"],
                ["title"=>"Guaraní","description"=>"Avañeẽ"],
                ["title"=>"Gujarati","description"=>"ગુજરાતી"],
                ["title"=>"Haitian; Haitian Creole","description"=>"Kreyòl ayisyen"],
                ["title"=>"Hausa","description"=>"Hausa, هَوُسَ"],
                ["title"=>"Hebrew (modern)","description"=>"עברית"],
                ["title"=>"Herero","description"=>"Otjiherero"],
                ["title"=>"Hindi","description"=>"हिन्दी, हिंदी"],
                ["title"=>"Hiri Motu","description"=>"Hiri Motu"],
                ["title"=>"Hungarian","description"=>"Magyar"],
                ["title"=>"Interlingua","description"=>"Interlingua"],
                ["title"=>"Indonesian","description"=>"Bahasa Indonesia"],
                ["title"=>"Interlingue","description"=>"Originally called Occidental; then Interlingue after WWII"],
                ["title"=>"Irish","description"=>"Gaeilge"],
                ["title"=>"Igbo","description"=>"Asụsụ Igbo"],
                ["title"=>"Inupiaq","description"=>"Iñupiaq, Iñupiatun"],
                ["title"=>"Ido","description"=>"Ido"],
                ["title"=>"Icelandic","description"=>"Íslenska"],
                ["title"=>"Italian","description"=>"Italiano"],
                ["title"=>"Inuktitut","description"=>"ᐃᓄᒃᑎᑐᑦ"],
                ["title"=>"Japanese","description"=>"日本語 (にほんご／にっぽんご)"],
                ["title"=>"Javanese","description"=>"basa Jawa"],
                ["title"=>"Kalaallisut, Greenlandic","description"=>"kalaallisut, kalaallit oqaasii"],
                ["title"=>"Kannada","description"=>"ಕನ್ನಡ"],
                ["title"=>"Kanuri","description"=>"Kanuri"],
                ["title"=>"Kashmiri","description"=>"कश्मीरी, كشميري‎"],
                ["title"=>"Kazakh","description"=>"Қазақ тілі"],
                ["title"=>"Khmer","description"=>"ភាសាខ្មែរ"],
                ["title"=>"Kikuyu, Gikuyu","description"=>"Gĩkũyũ"],
                ["title"=>"Kinyarwanda","description"=>"Ikinyarwanda"],
                ["title"=>"Kirghiz, Kyrgyz","description"=>"кыргыз тили"],
                ["title"=>"Komi","description"=>"коми кыв"],
                ["title"=>"Kongo","description"=>"KiKongo"],
                ["title"=>"Korean","description"=>"한국어 (韓國語), 조선말 (朝鮮語)"],
                ["title"=>"Kurdish","description"=>"Kurdî, كوردی‎"],
                ["title"=>"Kwanyama, Kuanyama","description"=>"Kuanyama"],
                ["title"=>"Latin","description"=>"latine, lingua latina"],
                ["title"=>"Luxembourgish, Letzeburgesch","description"=>"Lëtzebuergesch"],
                ["title"=>"Luganda","description"=>"Luganda"],
                ["title"=>"Limburgish, Limburgan, Limburger","description"=>"Limburgs"],
                ["title"=>"Lingala","description"=>"Lingála"],
                ["title"=>"Lao","description"=>"ພາສາລາວ"],
                ["title"=>"Lithuanian","description"=>"lietuvių kalba"],
                ["title"=>"Luba-Katanga","description"=>""],
                ["title"=>"Latvian","description"=>"latviešu valoda"],
                ["title"=>"Manx","description"=>"Gaelg, Gailck"],
                ["title"=>"Macedonian","description"=>"македонски јазик"],
                ["title"=>"Malagasy","description"=>"Malagasy fiteny"],
                ["title"=>"Malay","description"=>"bahasa Melayu, بهاس ملايو‎"],
                ["title"=>"Malayalam","description"=>"മലയാളം"],
                ["title"=>"Maltese","description"=>"Malti"],
                ["title"=>"Māori","description"=>"te reo Māori"],
                ["title"=>"Marathi (Marāṭhī)","description"=>"मराठी"],
                ["title"=>"Marshallese","description"=>"Kajin M̧ajeļ"],
                ["title"=>"Mongolian","description"=>"монгол"],
                ["title"=>"Nauru","description"=>"Ekakairũ Naoero"],
                ["title"=>"Navajo, Navaho","description"=>"Diné bizaad, Dinékʼehǰí"],
                ["title"=>"Norwegian Bokmål","description"=>"Norsk bokmål"],
                ["title"=>"North Ndebele","description"=>"isiNdebele"],
                ["title"=>"Nepali","description"=>"नेपाली"],
                ["title"=>"Ndonga","description"=>"Owambo"],
                ["title"=>"Norwegian Nynorsk","description"=>"Norsk nynorsk"],
                ["title"=>"Norwegian","description"=>"Norsk"],
                ["title"=>"Nuosu","description"=>"ꆈꌠ꒿ Nuosuhxop"],
                ["title"=>"South Ndebele","description"=>"isiNdebele"],
                ["title"=>"Occitan","description"=>"Occitan"],
                ["title"=>"Ojibwe, Ojibwa","description"=>"ᐊᓂᔑᓈᐯᒧᐎᓐ"],
                ["title"=>"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic","description"=>"ѩзыкъ словѣньскъ"],
                ["title"=>"Oromo","description"=>"Afaan Oromoo"],
                ["title"=>"Oriya","description"=>"ଓଡ଼ିଆ"],
                ["title"=>"Ossetian, Ossetic","description"=>"ирон æвзаг"],
                ["title"=>"Panjabi, Punjabi","description"=>"ਪੰਜਾਬੀ, پنجابی‎"],
                ["title"=>"Pāli","description"=>"पाऴि"],
                ["title"=>"Persian","description"=>"فارسی"],
                ["title"=>"Polish","description"=>"polski"],
                ["title"=>"Pashto, Pushto","description"=>"پښتو"],
                ["title"=>"Portuguese","description"=>"Português"],
                ["title"=>"Quechua","description"=>"Runa Simi, Kichwa"],
                ["title"=>"Romansh","description"=>"rumantsch grischun"],
                ["title"=>"Kirundi","description"=>"kiRundi"],
                ["title"=>"Romanian, Moldavian, Moldovan","description"=>"română"],
                ["title"=>"Russian","description"=>"русский язык"],
                ["title"=>"Sanskrit (Saṁskṛta)","description"=>"संस्कृतम्"],
                ["title"=>"Sardinian","description"=>"sardu"],
                ["title"=>"Sindhi","description"=>"सिन्धी, سنڌي، سندھی‎"],
                ["title"=>"Northern Sami","description"=>"Davvisámegiella"],
                ["title"=>"Samoan","description"=>"gagana faa Samoa"],
                ["title"=>"Sango","description"=>"yângâ tî sängö"],
                ["title"=>"Serbian","description"=>"српски језик"],
                ["title"=>"Scottish Gaelic; Gaelic","description"=>"Gàidhlig"],
                ["title"=>"Shona","description"=>"chiShona"],
                ["title"=>"Sinhala, Sinhalese","description"=>"සිංහල"],
                ["title"=>"Slovak","description"=>"slovenčina"],
                ["title"=>"Slovene","description"=>"slovenščina"],
                ["title"=>"Somali","description"=>"Soomaaliga, af Soomaali"],
                ["title"=>"Southern Sotho","description"=>"Sesotho"],
                ["title"=>"Spanish; Castilian","description"=>"español, castellano"],
                ["title"=>"Sundanese","description"=>"Basa Sunda"],
                ["title"=>"Swahili","description"=>"Kiswahili"],
                ["title"=>"Swati","description"=>"SiSwati"],
                ["title"=>"Swedish","description"=>"svenska"],
                ["title"=>"Tamil","description"=>"தமிழ்"],
                ["title"=>"Telugu","description"=>"తెలుగు"],
                ["title"=>"Tajik","description"=>"тоҷикӣ, toğikī, تاجیکی‎"],
                ["title"=>"Thai","description"=>"ไทย"],
                ["title"=>"Tigrinya","description"=>"ትግርኛ"],
                ["title"=>"Tibetan Standard, Tibetan, Central","description"=>"བོད་ཡིག"],
                ["title"=>"Turkmen","description"=>"Türkmen, Түркмен"],
                ["title"=>"Tagalog","description"=>"Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"],
                ["title"=>"Tswana","description"=>"Setswana"],
                ["title"=>"Tonga (Tonga Islands)","description"=>"faka Tonga"],
                ["title"=>"Turkish","description"=>"Türkçe"],
                ["title"=>"Tsonga","description"=>"Xitsonga"],
                ["title"=>"Tatar","description"=>"татарча, tatarça, تاتارچا‎"],
                ["title"=>"Twi","description"=>"Twi"],
                ["title"=>"Tahitian","description"=>"Reo Tahiti"],
                ["title"=>"Uighur, Uyghur","description"=>"Uyƣurqə, ئۇيغۇرچە‎"],
                ["title"=>"Ukrainian","description"=>"українська"],
                ["title"=>"Urdu","description"=>"اردو"],
                ["title"=>"Uzbek","description"=>"zbek, Ўзбек, أۇزبېك‎"],
                ["title"=>"Venda","description"=>"Tshivenḓa"],
                ["title"=>"Viettitlese","description"=>"Tiếng Việt"],
                ["title"=>"Volapük","description"=>"Volapük"],
                ["title"=>"Walloon","description"=>"Walon"],
                ["title"=>"Welsh","description"=>"Cymraeg"],
                ["title"=>"Wolof","description"=>"Wollof"],
                ["title"=>"Western Frisian","description"=>"Frysk"],
                ["title"=>"Xhosa","description"=>"isiXhosa"],
                ["title"=>"Yiddish","description"=>"ייִדיש"],
                ["title"=>"Yoruba","description"=>"Yorùbá"],
                ["title"=>"Zhuang, Chuang","description"=>"Saɯ cueŋƅ, Saw cuengh"]
        ];
        DB::table('languages')->delete();

        DB::table('languages')->insert($languages);
    }
}
