<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $languages = [
            ["title" => "Abkhaz", "description" => "аҧсуа"],
            ["title" => "Afar", "description" => "Afaraf"],
            ["title" => "Afrikaans", "description" => "Afrikaans"],
            ["title" => "Akan", "description" => "Akan"],
            ["title" => "Albanian", "description" => "Shqip"],
            ["title" => "Amharic", "description" => "አማርኛ"],
            ["title" => "Arabic", "description" => "العربية"],
            ["title" => "Aragonese", "description" => "Aragonés"],
            ["title" => "Armenian", "description" => "Հայերեն"],
            ["title" => "Assamese", "description" => "অসমীয়া"],
            ["title" => "Avaric", "description" => "авар мацӀ, магӀарул мацӀ"],
            ["title" => "Avestan", "description" => "avesta"],
            ["title" => "Aymara", "description" => "aymar aru"],
            ["title" => "Azerbaijani", "description" => "azərbaycan dili"],
            ["title" => "Bambara", "description" => "bamanankan"],
            ["title" => "Bashkir", "description" => "башҡорт теле"],
            ["title" => "Basque", "description" => "euskara, euskera"],
            ["title" => "Belarusian", "description" => "Беларуская"],
            ["title" => "Bengali", "description" => "বাংলা"],
            ["title" => "Bihari", "description" => "भोजपुरी"],
            ["title" => "Bislama", "description" => "Bislama"],
            ["title" => "Bosnian", "description" => "bosanski jezik"],
            ["title" => "Breton", "description" => "brezhoneg"],
            ["title" => "Bulgarian", "description" => "български език"],
            ["title" => "Burmese", "description" => "ဗမာစာ"],
            ["title" => "Catalan; Valencian", "description" => "Català"],
            ["title" => "Chamorro", "description" => "Chamoru"],
            ["title" => "Chechen", "description" => "нохчийн мотт"],
            ["title" => "Chichewa; Chewa; Nyanja", "description" => "chiCheŵa, chinyanja"],
            ["title" => "Chinese", "description" => "中文 (Zhōngwén), 汉语, 漢語"],
            ["title" => "Chuvash", "description" => "чӑваш чӗлхи"],
            ["title" => "Cornish", "description" => "Kernewek"],
            ["title" => "Corsican", "description" => "corsu, lingua corsa"],
            ["title" => "Cree", "description" => "ᓀᐦᐃᔭᐍᐏᐣ"],
            ["title" => "Croatian", "description" => "hrvatski"],
            ["title" => "Czech", "description" => "česky, čeština"],
            ["title" => "Danish", "description" => "dansk"],
            ["title" => "Divehi; Dhivehi; Maldivian;", "description" => "ދިވެހި"],
            ["title" => "Dutch", "description" => "Nederlands, Vlaams"],
            ["title" => "English", "description" => "English"],
            ["title" => "Esperanto", "description" => "Esperanto"],
            ["title" => "Estonian", "description" => "eesti, eesti keel"],
            ["title" => "Ewe", "description" => "Eʋegbe"],
            ["title" => "Faroese", "description" => "føroyskt"],
            ["title" => "Fijian", "description" => "vosa Vakaviti"],
            ["title" => "Finnish", "description" => "suomi, suomen kieli"],
            ["title" => "French", "description" => "français, langue française"],
            ["title" => "Fula; Fulah; Pulaar; Pular", "description" => "Fulfulde, Pulaar, Pular"],
            ["title" => "Galician", "description" => "Galego"],
            ["title" => "Georgian", "description" => "ქართული"],
            ["title" => "German", "description" => "Deutsch"],
            ["title" => "Greek, Modern", "description" => "Ελληνικά"],
            ["title" => "Guaraní", "description" => "Avañeẽ"],
            ["title" => "Gujarati", "description" => "ગુજરાતી"],
            ["title" => "Haitian; Haitian Creole", "description" => "Kreyòl ayisyen"],
            ["title" => "Hausa", "description" => "Hausa, هَوُسَ"],
            ["title" => "Hebrew (modern)", "description" => "עברית"],
            ["title" => "Herero", "description" => "Otjiherero"],
            ["title" => "Hindi", "description" => "हिन्दी, हिंदी"],
            ["title" => "Hiri Motu", "description" => "Hiri Motu"],
            ["title" => "Hungarian", "description" => "Magyar"],
            ["title" => "Interlingua", "description" => "Interlingua"],
            ["title" => "Indonesian", "description" => "Bahasa Indonesia"],
            ["title" => "Interlingue", "description" => "Originally called Occidental; then Interlingue after WWII"],
            ["title" => "Irish", "description" => "Gaeilge"],
            ["title" => "Igbo", "description" => "Asụsụ Igbo"],
            ["title" => "Inupiaq", "description" => "Iñupiaq, Iñupiatun"],
            ["title" => "Ido", "description" => "Ido"],
            ["title" => "Icelandic", "description" => "Íslenska"],
            ["title" => "Italian", "description" => "Italiano"],
            ["title" => "Inuktitut", "description" => "ᐃᓄᒃᑎᑐᑦ"],
            ["title" => "Japanese", "description" => "日本語 (にほんご／にっぽんご)"],
            ["title" => "Javanese", "description" => "basa Jawa"],
            ["title" => "Kalaallisut, Greenlandic", "description" => "kalaallisut, kalaallit oqaasii"],
            ["title" => "Kannada", "description" => "ಕನ್ನಡ"],
            ["title" => "Kanuri", "description" => "Kanuri"],
            ["title" => "Kashmiri", "description" => "कश्मीरी, كشميري‎"],
            ["title" => "Kazakh", "description" => "Қазақ тілі"],
            ["title" => "Khmer", "description" => "ភាសាខ្មែរ"],
            ["title" => "Kikuyu, Gikuyu", "description" => "Gĩkũyũ"],
            ["title" => "Kinyarwanda", "description" => "Ikinyarwanda"],
            ["title" => "Kirghiz, Kyrgyz", "description" => "кыргыз тили"],
            ["title" => "Komi", "description" => "коми кыв"],
            ["title" => "Kongo", "description" => "KiKongo"],
            ["title" => "Korean", "description" => "한국어 (韓國語), 조선말 (朝鮮語)"],
            ["title" => "Kurdish", "description" => "Kurdî, كوردی‎"],
            ["title" => "Kwanyama, Kuanyama", "description" => "Kuanyama"],
            ["title" => "Latin", "description" => "latine, lingua latina"],
            ["title" => "Luxembourgish, Letzeburgesch", "description" => "Lëtzebuergesch"],
            ["title" => "Luganda", "description" => "Luganda"],
            ["title" => "Limburgish, Limburgan, Limburger", "description" => "Limburgs"],
            ["title" => "Lingala", "description" => "Lingála"],
            ["title" => "Lao", "description" => "ພາສາລາວ"],
            ["title" => "Lithuanian", "description" => "lietuvių kalba"],
            ["title" => "Luba-Katanga", "description" => ""],
            ["title" => "Latvian", "description" => "latviešu valoda"],
            ["title" => "Manx", "description" => "Gaelg, Gailck"],
            ["title" => "Macedonian", "description" => "македонски јазик"],
            ["title" => "Malagasy", "description" => "Malagasy fiteny"],
            ["title" => "Malay", "description" => "bahasa Melayu, بهاس ملايو‎"],
            ["title" => "Malayalam", "description" => "മലയാളം"],
            ["title" => "Maltese", "description" => "Malti"],
            ["title" => "Māori", "description" => "te reo Māori"],
            ["title" => "Marathi (Marāṭhī)", "description" => "मराठी"],
            ["title" => "Marshallese", "description" => "Kajin M̧ajeļ"],
            ["title" => "Mongolian", "description" => "монгол"],
            ["title" => "Nauru", "description" => "Ekakairũ Naoero"],
            ["title" => "Navajo, Navaho", "description" => "Diné bizaad, Dinékʼehǰí"],
            ["title" => "Norwegian Bokmål", "description" => "Norsk bokmål"],
            ["title" => "North Ndebele", "description" => "isiNdebele"],
            ["title" => "Nepali", "description" => "नेपाली"],
            ["title" => "Ndonga", "description" => "Owambo"],
            ["title" => "Norwegian Nynorsk", "description" => "Norsk nynorsk"],
            ["title" => "Norwegian", "description" => "Norsk"],
            ["title" => "Nuosu", "description" => "ꆈꌠ꒿ Nuosuhxop"],
            ["title" => "South Ndebele", "description" => "isiNdebele"],
            ["title" => "Occitan", "description" => "Occitan"],
            ["title" => "Ojibwe, Ojibwa", "description" => "ᐊᓂᔑᓈᐯᒧᐎᓐ"],
            ["title" => "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic", "description" => "ѩзыкъ словѣньскъ"],
            ["title" => "Oromo", "description" => "Afaan Oromoo"],
            ["title" => "Oriya", "description" => "ଓଡ଼ିଆ"],
            ["title" => "Ossetian, Ossetic", "description" => "ирон æвзаг"],
            ["title" => "Panjabi, Punjabi", "description" => "ਪੰਜਾਬੀ, پنجابی‎"],
            ["title" => "Pāli", "description" => "पाऴि"],
            ["title" => "Persian", "description" => "فارسی"],
            ["title" => "Polish", "description" => "polski"],
            ["title" => "Pashto, Pushto", "description" => "پښتو"],
            ["title" => "Portuguese", "description" => "Português"],
            ["title" => "Quechua", "description" => "Runa Simi, Kichwa"],
            ["title" => "Romansh", "description" => "rumantsch grischun"],
            ["title" => "Kirundi", "description" => "kiRundi"],
            ["title" => "Romanian, Moldavian, Moldovan", "description" => "română"],
            ["title" => "Russian", "description" => "русский язык"],
            ["title" => "Sanskrit (Saṁskṛta)", "description" => "संस्कृतम्"],
            ["title" => "Sardinian", "description" => "sardu"],
            ["title" => "Sindhi", "description" => "सिन्धी, سنڌي، سندھی‎"],
            ["title" => "Northern Sami", "description" => "Davvisámegiella"],
            ["title" => "Samoan", "description" => "gagana faa Samoa"],
            ["title" => "Sango", "description" => "yângâ tî sängö"],
            ["title" => "Serbian", "description" => "српски језик"],
            ["title" => "Scottish Gaelic; Gaelic", "description" => "Gàidhlig"],
            ["title" => "Shona", "description" => "chiShona"],
            ["title" => "Sinhala, Sinhalese", "description" => "සිංහල"],
            ["title" => "Slovak", "description" => "slovenčina"],
            ["title" => "Slovene", "description" => "slovenščina"],
            ["title" => "Somali", "description" => "Soomaaliga, af Soomaali"],
            ["title" => "Southern Sotho", "description" => "Sesotho"],
            ["title" => "Spanish; Castilian", "description" => "español, castellano"],
            ["title" => "Sundanese", "description" => "Basa Sunda"],
            ["title" => "Swahili", "description" => "Kiswahili"],
            ["title" => "Swati", "description" => "SiSwati"],
            ["title" => "Swedish", "description" => "svenska"],
            ["title" => "Tamil", "description" => "தமிழ்"],
            ["title" => "Telugu", "description" => "తెలుగు"],
            ["title" => "Tajik", "description" => "тоҷикӣ, toğikī, تاجیکی‎"],
            ["title" => "Thai", "description" => "ไทย"],
            ["title" => "Tigrinya", "description" => "ትግርኛ"],
            ["title" => "Tibetan Standard, Tibetan, Central", "description" => "བོད་ཡིག"],
            ["title" => "Turkmen", "description" => "Türkmen, Түркмен"],
            ["title" => "Tagalog", "description" => "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"],
            ["title" => "Tswana", "description" => "Setswana"],
            ["title" => "Tonga (Tonga Islands)", "description" => "faka Tonga"],
            ["title" => "Turkish", "description" => "Türkçe"],
            ["title" => "Tsonga", "description" => "Xitsonga"],
            ["title" => "Tatar", "description" => "татарча, tatarça, تاتارچا‎"],
            ["title" => "Twi", "description" => "Twi"],
            ["title" => "Tahitian", "description" => "Reo Tahiti"],
            ["title" => "Uighur, Uyghur", "description" => "Uyƣurqə, ئۇيغۇرچە‎"],
            ["title" => "Ukrainian", "description" => "українська"],
            ["title" => "Urdu", "description" => "اردو"],
            ["title" => "Uzbek", "description" => "zbek, Ўзбек, أۇزبېك‎"],
            ["title" => "Venda", "description" => "Tshivenḓa"],
            ["title" => "Viettitlese", "description" => "Tiếng Việt"],
            ["title" => "Volapük", "description" => "Volapük"],
            ["title" => "Walloon", "description" => "Walon"],
            ["title" => "Welsh", "description" => "Cymraeg"],
            ["title" => "Wolof", "description" => "Wollof"],
            ["title" => "Western Frisian", "description" => "Frysk"],
            ["title" => "Xhosa", "description" => "isiXhosa"],
            ["title" => "Yiddish", "description" => "ייִדיש"],
            ["title" => "Yoruba", "description" => "Yorùbá"],
            ["title" => "Zhuang, Chuang", "description" => "Saɯ cueŋƅ, Saw cuengh"],
            ["title" => "Abanyom", "description" => "Abanyom"],
            ["title" => "Abon", "description" => "Abon"],
            ["title" => "Abua", "description" => "Abua"],
            ["title" => "Abureni", "description" => "Abureni"],
            ["title" => "Achipa", "description" => "Achipa"],
            ["title" => "Adim", "description" => "Adim"],
            ["title" => "Aduge", "description" => "Aduge"],
            ["title" => "Adun", "description" => "Adun"],
            ["title" => "Afade", "description" => "Afade"],
            ["title" => "Afo", "description" => "Afo"],
            ["title" => "Afrike", "description" => "Afrike"],
            ["title" => "Ajawa", "description" => "Ajawa"],
            ["title" => "Akaju-Ndem", "description" => "Akaju-Ndem"],
            ["title" => "Akweya-Yachi", "description" => "Akweya-Yachi"],
            ["title" => "Alago", "description" => "Alago"],
            ["title" => "Amo", "description" => "Amo"],
            ["title" => "Anaguta", "description" => "Anaguta"],
            ["title" => "Anang", "description" => "Anang"],
            ["title" => "Angas", "description" => "Angas"],
            ["title" => "Ankwei", "description" => "Ankwei"],
            ["title" => "Chadian_Arabic", "description" => "Chadian_Arabic"],
            ["title" => "Anyima", "description" => "Anyima"],
            ["title" => "Arum", "description" => "Arum"],
            ["title" => "Attakar", "description" => "Attakar"],
            ["title" => "Auyoka", "description" => "Auyoka"],
            ["title" => "Awori", "description" => "Awori"],
            ["title" => "Ayu", "description" => "Ayu"],
            ["title" => "Babur", "description" => "Babur"],
            ["title" => "Bacama language", "description" => "Bacama language"],
            ["title" => "Bachere", "description" => "Bachere"],
            ["title" => "Bada", "description" => "Bada"],
            ["title" => "Bade language", "description" => "Bade language"],
            ["title" => "Bakulung", "description" => "Bakulung"],
            ["title" => "Bali", "description" => "Bali"],
            ["title" => "Bambora", "description" => "Bambora"],
            ["title" => "Bambuko", "description" => "Bambuko"],
            ["title" => "Banda", "description" => "Banda"],
            ["title" => "Banka", "description" => "Banka"],
            ["title" => "Banso", "description" => "Banso"],
            ["title" => "Bara", "description" => "Bara"],
            ["title" => "Barke", "description" => "Barke"],
            ["title" => "Baruba", "description" => "Baruba"],
            ["title" => "Bashiri", "description" => "Bashiri"],
            ["title" => "Basa", "description" => "Basa"],
            ["title" => "Bata", "description" => "Bata"],
            ["title" => "Baushi", "description" => "Baushi"],
            ["title" => "Baya", "description" => "Baya"],
            ["title" => "Bekwarra", "description" => "Bekwarra"],
            ["title" => "Bele", "description" => "Bele"],
            ["title" => "Betso", "description" => "Betso"],
            ["title" => "Bette", "description" => "Bette"],
            ["title" => "Bilei", "description" => "Bilei"],
            ["title" => "Bille", "description" => "Bille"],
            ["title" => "Bina", "description" => "Bina"],
            ["title" => "Bini", "description" => "Bini"],
            ["title" => "Berom", "description" => "Berom"],
            ["title" => "Bobua", "description" => "Bobua"],
            ["title" => "Boki", "description" => "Boki"],
            ["title" => "Bokkos", "description" => "Bokkos"],
            ["title" => "Boko", "description" => "Boko"],
            ["title" => "Bole", "description" => "Bole"],
            ["title" => "Botlere", "description" => "Botlere"],
            ["title" => "Boma", "description" => "Boma"],
            ["title" => "Bomboro", "description" => "Bomboro"],
            ["title" => "Buduma", "description" => "Buduma"],
            ["title" => "Buji", "description" => "Buji"],
            ["title" => "Buli", "description" => "Buli"],
            ["title" => "Bunu", "description" => "Bunu"],
            ["title" => "Bura", "description" => "Bura"],
            ["title" => "Burak", "description" => "Burak"],
            ["title" => "Burma", "description" => "Burma"],
            ["title" => "Buru", "description" => "Buru"],
            ["title" => "Buta", "description" => "Buta"],
            ["title" => "Bwall", "description" => "Bwall"],
            ["title" => "Bwatiye", "description" => "Bwatiye"],
            ["title" => "Bwazza", "description" => "Bwazza"],
            ["title" => "Challa", "description" => "Challa"],
            ["title" => "Chama", "description" => "Chama"],
            ["title" => "Chamba", "description" => "Chamba"],
            ["title" => "Chamo", "description" => "Chamo"],
            ["title" => "Cibak", "description" => "Cibak"],
            ["title" => "Chinine", "description" => "Chinine"],
            ["title" => "Chip", "description" => "Chip"],
            ["title" => "Chokobo", "description" => "Chokobo"],
            ["title" => "Chukkol", "description" => "Chukkol"],
            ["title" => "Cipu", "description" => "Cipu"],
            ["title" => "Daba", "description" => "Daba"],
            ["title" => "Dadiya", "description" => "Dadiya"],
            ["title" => "Daka", "description" => "Daka"],
            ["title" => "Dakarkari", "description" => "Dakarkari"],
            ["title" => "Danda", "description" => "Danda"],
            ["title" => "Dangsa", "description" => "Dangsa"],
            ["title" => "Daza", "description" => "Daza"],
            ["title" => "Degema", "description" => "Degema"],
            ["title" => "Deno", "description" => "Deno"],
            ["title" => "Dghwede", "description" => "Dghwede"],
            ["title" => "Diba", "description" => "Diba"],
            ["title" => "Doemak", "description" => "Doemak"],
            ["title" => "Duguri", "description" => "Duguri"],
            ["title" => "Duka", "description" => "Duka"],
            ["title" => "Duma", "description" => "Duma"],
            ["title" => "Ebana", "description" => "Ebana"],
            ["title" => "Ebirra", "description" => "Ebirra"],
            ["title" => "Ebu", "description" => "Ebu"],
            ["title" => "Efik", "description" => "Efik"],
            ["title" => "Egbema", "description" => "Egbema"],
            ["title" => "Eggon", "description" => "Eggon"],
            ["title" => "Egun", "description" => "Egun"],
            ["title" => "Ejagham", "description" => "Ejagham"],
            ["title" => "Ekajuk", "description" => "Ekajuk"],
            ["title" => "Eket", "description" => "Eket"],
            ["title" => "Ekoi", "description" => "Ekoi"],
            ["title" => "Ekpeye", "description" => "Ekpeye"],
            ["title" => "Engenni", "description" => "Engenni"],
            ["title" => "Epie", "description" => "Epie"],
            ["title" => "Esan", "description" => "Esan"],
            ["title" => "Etche", "description" => "Etche"],
            ["title" => "Etolu", "description" => "Etolu"],
            ["title" => "Etsako", "description" => "Etsako"],
            ["title" => "Etung", "description" => "Etung"],
            ["title" => "Etuno", "description" => "Etuno"],
            ["title" => "Falli", "description" => "Falli"],
            ["title" => "Fula", "description" => "Fula"],
            ["title" => "Fyam", "description" => "Fyam"],
            ["title" => "Fyer", "description" => "Fyer"],
            ["title" => "Ga�anda", "description" => "Ga�anda"],
            ["title" => "Gade", "description" => "Gade"],
            ["title" => "Galambi", "description" => "Galambi"],
            ["title" => "Gamergu", "description" => "Gamergu"],
            ["title" => "Ganawuri", "description" => "Ganawuri"],
            ["title" => "Gavako", "description" => "Gavako"],
            ["title" => "Gbedde", "description" => "Gbedde"],
            ["title" => "Gbo", "description" => "Gbo"],
            ["title" => "Gengle", "description" => "Gengle"],
            ["title" => "Geji", "description" => "Geji"],
            ["title" => "Gera", "description" => "Gera"],
            ["title" => "Geruma", "description" => "Geruma"],
            ["title" => "Gingwak", "description" => "Gingwak"],
            ["title" => "Gira", "description" => "Gira"],
            ["title" => "Gizigz", "description" => "Gizigz"],
            ["title" => "Goernai", "description" => "Goernai"],
            ["title" => "Gokana", "description" => "Gokana"],
            ["title" => "Gombi", "description" => "Gombi"],
            ["title" => "Gornun", "description" => "Gornun"],
            ["title" => "Gonia", "description" => "Gonia"],
            ["title" => "Gubi", "description" => "Gubi"],
            ["title" => "Gude", "description" => "Gude"],
            ["title" => "Gudu", "description" => "Gudu"],
            ["title" => "Gure", "description" => "Gure"],
            ["title" => "Gurmana", "description" => "Gurmana"],
            ["title" => "Gururntum", "description" => "Gururntum"],
            ["title" => "Gusu", "description" => "Gusu"],
            ["title" => "Gwa", "description" => "Gwa"],
            ["title" => "Gwamba", "description" => "Gwamba"],
            ["title" => "Gwari", "description" => "Gwari"],
            ["title" => "Gwom", "description" => "Gwom"],
            ["title" => "Gwoza", "description" => "Gwoza"],
            ["title" => "Gyem", "description" => "Gyem"],
            ["title" => "Humono", "description" => "Humono"],
            ["title" => "Holma", "description" => "Holma"],
            ["title" => "Hona", "description" => "Hona"],
            ["title" => "Hyam", "description" => "Hyam"],
            ["title" => "Ibeno", "description" => "Ibeno"],
            ["title" => "Ibibio", "description" => "Ibibio"],
            ["title" => "Ichen", "description" => "Ichen"],
            ["title" => "Idoma", "description" => "Idoma"],
            ["title" => "Igala", "description" => "Igala"],
            ["title" => "Igede", "description" => "Igede"],
            ["title" => "Ijaw", "description" => "Ijaw"],
            ["title" => "Ijumu", "description" => "Ijumu"],
            ["title" => "Ika", "description" => "Ika"],
            ["title" => "Ikorn", "description" => "Ikorn"],
            ["title" => "Irigwe", "description" => "Irigwe"],
            ["title" => "Isoko", "description" => "Isoko"],
            ["title" => "Isekiri", "description" => "Isekiri"],
            ["title" => "Iyala", "description" => "Iyala"],
            ["title" => "Izere", "description" => "Izere"],
            ["title" => "Plateau", "description" => "Plateau"],
            ["title" => "Izondjo", "description" => "Izondjo"],
            ["title" => "Jahuna", "description" => "Jahuna"],
            ["title" => "Jaku", "description" => "Jaku"],
            ["title" => "Jara", "description" => "Jara"],
            ["title" => "Jibu", "description" => "Jibu"],
            ["title" => "Jidda-Abu", "description" => "Jidda-Abu"],
            ["title" => "Jimbin", "description" => "Jimbin"],
            ["title" => "Jirai", "description" => "Jirai"],
            ["title" => "Jju", "description" => "Jju"],
            ["title" => "Kaje", "description" => "Kaje"],
            ["title" => "Jonjo", "description" => "Jonjo"],
            ["title" => "Jukun", "description" => "Jukun"],
            ["title" => "Kaba", "description" => "Kaba"],
            ["title" => "Kadara", "description" => "Kadara"],
            ["title" => "Kafanchan", "description" => "Kafanchan"],
            ["title" => "Kagoro", "description" => "Kagoro"],
            ["title" => "Kaka", "description" => "Kaka"],
            ["title" => "Kamaku", "description" => "Kamaku"],
            ["title" => "Kambari", "description" => "Kambari"],
            ["title" => "Kamwe", "description" => "Kamwe"],
            ["title" => "Kamo", "description" => "Kamo"],
            ["title" => "Kanakuru", "description" => "Kanakuru"],
            ["title" => "Kanembu", "description" => "Kanembu"],
            ["title" => "Kanikon", "description" => "Kanikon"],
            ["title" => "Kantana", "description" => "Kantana"],
            ["title" => "Kanufi", "description" => "Kanufi"],
            ["title" => "Kanuri", "description" => "Kanuri"],
            ["title" => "Karekare", "description" => "Karekare"],
            ["title" => "Karimjo", "description" => "Karimjo"],
            ["title" => "Kariya", "description" => "Kariya"],
            ["title" => "Katab", "description" => "Katab"],
            ["title" => "Kenern", "description" => "Kenern"],
            ["title" => "Kenton", "description" => "Kenton"],
            ["title" => "Kiballo", "description" => "Kiballo"],
            ["title" => "Kilba", "description" => "Kilba"],
            ["title" => "Kirfi", "description" => "Kirfi"],
            ["title" => "Koma", "description" => "Koma"],
            ["title" => "Koro", "description" => "Koro"],
            ["title" => "Kubi", "description" => "Kubi"],
            ["title" => "Kudachano", "description" => "Kudachano"],
            ["title" => "Kulere", "description" => "Kulere"],
            ["title" => "Kunini", "description" => "Kunini"],
            ["title" => "Kurama", "description" => "Kurama"],
            ["title" => "Kurdul", "description" => "Kurdul"],
            ["title" => "Kushi", "description" => "Kushi"],
            ["title" => "Kuteb", "description" => "Kuteb"],
            ["title" => "Kutin", "description" => "Kutin"],
            ["title" => "Kwah", "description" => "Kwah"],
            ["title" => "Kwalla", "description" => "Kwalla"],
            ["title" => "Kwami", "description" => "Kwami"],
            ["title" => "Kwanchi", "description" => "Kwanchi"],
            ["title" => "Kwanka", "description" => "Kwanka"],
            ["title" => "Kwaro", "description" => "Kwaro"],
            ["title" => "Kyenga", "description" => "Kyenga"],
            ["title" => "Laaru", "description" => "Laaru"],
            ["title" => "Lakka", "description" => "Lakka"],
            ["title" => "Lala", "description" => "Lala"],
            ["title" => "Lamja", "description" => "Lamja"],
            ["title" => "Lopa", "description" => "Lopa"],
            ["title" => "Longuda", "description" => "Longuda"],
            ["title" => "Mabo", "description" => "Mabo"],
            ["title" => "Mada", "description" => "Mada"],
            ["title" => "Mama", "description" => "Mama"],
            ["title" => "Mambilla", "description" => "Mambilla"],
            ["title" => "Manchok", "description" => "Manchok"],
            ["title" => "Mandara", "description" => "Mandara"],
            ["title" => "Manga", "description" => "Manga"],
            ["title" => "Margi", "description" => "Margi"],
            ["title" => "Matakarn", "description" => "Matakarn"],
            ["title" => "Mbembe", "description" => "Mbembe"],
            ["title" => "Mbol", "description" => "Mbol"],
            ["title" => "Mbube", "description" => "Mbube"],
            ["title" => "Mbula", "description" => "Mbula"],
            ["title" => "Mbum", "description" => "Mbum"],
            ["title" => "Memyang", "description" => "Memyang"],
            ["title" => "Miango", "description" => "Miango"],
            ["title" => "Miya", "description" => "Miya"],
            ["title" => "Mobber", "description" => "Mobber"],
            ["title" => "Montol", "description" => "Montol"],
            ["title" => "Moruwa", "description" => "Moruwa"],
            ["title" => "Muchaila", "description" => "Muchaila"],
            ["title" => "Mumuye", "description" => "Mumuye"],
            ["title" => "Mundang", "description" => "Mundang"],
            ["title" => "Mupun", "description" => "Mupun"],
            ["title" => "Mushere", "description" => "Mushere"],
            ["title" => "Mwahavul", "description" => "Mwahavul"],
            ["title" => "Ndoro", "description" => "Ndoro"],
            ["title" => "Ngamo", "description" => "Ngamo"],
            ["title" => "Ngizim", "description" => "Ngizim"],
            ["title" => "Ngweshe", "description" => "Ngweshe"],
            ["title" => "Ningi", "description" => "Ningi"],
            ["title" => "Ninzam", "description" => "Ninzam"],
            ["title" => "Njayi", "description" => "Njayi"],
            ["title" => "Nkim", "description" => "Nkim"],
            ["title" => "Nkum", "description" => "Nkum"],
            ["title" => "Nokere", "description" => "Nokere"],
            ["title" => "Nsukka", "description" => "Nsukka"],
            ["title" => "Nunku", "description" => "Nunku"],
            ["title" => "Nupe", "description" => "Nupe"],
            ["title" => "Nyandang", "description" => "Nyandang"],
            ["title" => "Obolo", "description" => "Obolo"],
            ["title" => "Ogba", "description" => "Ogba"],
            ["title" => "Ogbia", "description" => "Ogbia"],
            ["title" => "Ododop", "description" => "Ododop"],
            ["title" => "Ogori", "description" => "Ogori"],
            ["title" => "Okobo", "description" => "Okobo"],
            ["title" => "Okpamheri", "description" => "Okpamheri"],
            ["title" => "Olulumo", "description" => "Olulumo"],
            ["title" => "Oro", "description" => "Oro"],
            ["title" => "Owan", "description" => "Owan"],
            ["title" => "Owe", "description" => "Owe"],
            ["title" => "Oworo", "description" => "Oworo"],
            ["title" => "Pa�a", "description" => "Pa�a"],
            ["title" => "Pai", "description" => "Pai"],
            ["title" => "Panyam", "description" => "Panyam"],
            ["title" => "Pero", "description" => "Pero"],
            ["title" => "Pire", "description" => "Pire"],
            ["title" => "Pkanzom", "description" => "Pkanzom"],
            ["title" => "Poll", "description" => "Poll"],
            ["title" => "Pongo", "description" => "Pongo"],
            ["title" => "Potopo", "description" => "Potopo"],
            ["title" => "Pyapun", "description" => "Pyapun"],
            ["title" => "Qua", "description" => "Qua"],
            ["title" => "Rebina", "description" => "Rebina"],
            ["title" => "Reshe", "description" => "Reshe"],
            ["title" => "Rindire", "description" => "Rindire"],
            ["title" => "Rishuwa", "description" => "Rishuwa"],
            ["title" => "Ron", "description" => "Ron"],
            ["title" => "Rubu", "description" => "Rubu"],
            ["title" => "Rukuba", "description" => "Rukuba"],
            ["title" => "Rumada", "description" => "Rumada"],
            ["title" => "Sakbe", "description" => "Sakbe"],
            ["title" => "Sanga", "description" => "Sanga"],
            ["title" => "Sate", "description" => "Sate"],
            ["title" => "Saya", "description" => "Saya"],
            ["title" => "Segidi", "description" => "Segidi"],
            ["title" => "Shanga", "description" => "Shanga"],
            ["title" => "Shangawa", "description" => "Shangawa"],
            ["title" => "Shan-Shan", "description" => "Shan-Shan"],
            ["title" => "Shira", "description" => "Shira"],
            ["title" => "Shomo", "description" => "Shomo"],
            ["title" => "Shuwa", "description" => "Shuwa"],
            ["title" => "Sikdi", "description" => "Sikdi"],
            ["title" => "Siri", "description" => "Siri"],
            ["title" => "Srubu", "description" => "Srubu"],
            ["title" => "Sukur", "description" => "Sukur"],
            ["title" => "Sura", "description" => "Sura"],
            ["title" => "Tangale", "description" => "Tangale"],
            ["title" => "Tarok", "description" => "Tarok"],
            ["title" => "Teme", "description" => "Teme"],
            ["title" => "Tera", "description" => "Tera"],
            ["title" => "Teshena", "description" => "Teshena"],
            ["title" => "Tigon", "description" => "Tigon"],
            ["title" => "Tikar", "description" => "Tikar"],
            ["title" => "Tiv", "description" => "Tiv"],
            ["title" => "Tula", "description" => "Tula"],
            ["title" => "Tur", "description" => "Tur"],
            ["title" => "Ufia", "description" => "Ufia"],
            ["title" => "Ukelle", "description" => "Ukelle"],
            ["title" => "Ukwani", "description" => "Ukwani"],
            ["title" => "Uncinda", "description" => "Uncinda"],
            ["title" => "Uneme", "description" => "Uneme"],
            ["title" => "Ura", "description" => "Ura"],
            ["title" => "Urhobo", "description" => "Urhobo"],
            ["title" => "Utonkong", "description" => "Utonkong"],
            ["title" => "Uvwie", "description" => "Uvwie"],
            ["title" => "Uyanga", "description" => "Uyanga"],
            ["title" => "Vemgo", "description" => "Vemgo"],
            ["title" => "Verre", "description" => "Verre"],
            ["title" => "Wagga", "description" => "Wagga"],
            ["title" => "Waja", "description" => "Waja"],
            ["title" => "Waka", "description" => "Waka"],
            ["title" => "Warja", "description" => "Warja"],
            ["title" => "Warji", "description" => "Warji"],
            ["title" => "Wula", "description" => "Wula"],
            ["title" => "Wurbo", "description" => "Wurbo"],
            ["title" => "Yache", "description" => "Yache"],
            ["title" => "Yagba", "description" => "Yagba"],
            ["title" => "Yakurr", "description" => "Yakurr"],
            ["title" => "Yalla", "description" => "Yalla"],
            ["title" => "Yandang", "description" => "Yandang"],
            ["title" => "Yergan", "description" => "Yergan"],
            ["title" => "Yott", "description" => "Yott"],
            ["title" => "Yumu", "description" => "Yumu"],
            ["title" => "Yungur", "description" => "Yungur"],
            ["title" => "Yuom", "description" => "Yuom"],
            ["title" => "Zabara", "description" => "Zabara"],
            ["title" => "Zaranda", "description" => "Zaranda"],
            ["title" => "Zarma", "description" => "Zarma"],
            ["title" => "Zayam", "description" => "Zayam"],
            ["title" => "Zul", "description" => "Zul"],
        ];
        DB::table('languages')->delete();

        DB::table('languages')->insert($languages);
    }
}
