<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocalGovtAreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('local_govt_areas')->delete();
        $local_govt_areas = [
            ["title" => "Demsa", "state_id" => 2649, "senatorial_zone_id" => 5],
            ["title" => "Fufure", "state_id" => 2649, "senatorial_zone_id" => 6],
            ["title" => "Ganye", "state_id" => 2649, "senatorial_zone_id" => 5],
            ["title" => "Gayuk", "state_id" => 2649, "senatorial_zone_id" => 5],
            ["title" => "Gombi", "state_id" => 2649, "senatorial_zone_id" =>4 ],
            ["title" => "Gerfi", "state_id" => 2649, "senatorial_zone_id" => 6],
            ["title" => "Hong", "state_id" => 2649, "senatorial_zone_id" => 6],
            ["title" => "Jada", "state_id" => 2649, "senatorial_zone_id" => 5],
            ["title" => "Larmurde", "state_id" => 2649, "senatorial_zone_id" => 5],
            ["title" => "Madagali", "state_id" => 2649, "senatorial_zone_id" => 4],
            ["title" => "Maiha", "state_id" => 2649, "senatorial_zone_id" => 4],
            ["title" => "Mayo Belwa", "state_id" => 2649, "senatorial_zone_id" => 5],
            ["title" => "Michika", "state_id" => 2649, "senatorial_zone_id" => 4],
            ["title" => "Mubi North", "state_id" => 2649, "senatorial_zone_id" => 4],
            ["title" => "Mubi South", "state_id" => 2649, "senatorial_zone_id" => 4],
            ["title" => "Numan", "state_id" => 2649, "senatorial_zone_id" => 5],
            ["title" => "Shelleng", "state_id" => 2649, "senatorial_zone_id" => 5],
            ["title" => "Song", "state_id" => 2649, "senatorial_zone_id" => 6],
            ["title" => "Toungo", "state_id" => 2649, "senatorial_zone_id" => 5],
            ["title" => "Yola North", "state_id" => 2649, "senatorial_zone_id" => 6],
            ["title" => "Yola South", "state_id" => 2649, "senatorial_zone_id" => 6],




            ["title" => "Abak", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Eastern Obolo", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Eket", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Esit Eket", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Essien Udim", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Etim Ekpo", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Etinan", "state_id" => 2650, "senatorial_zone_id" => 7],
            ["title" => "Ibeno", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Ibesikpo Asutan", "state_id" => 2650, "senatorial_zone_id" => 7],
            ["title" => "Ibiono Ibom", "state_id" => 2650, "senatorial_zone_id" => 7],
            ["title" => "Ikot Abasi", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Ika", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Ikono", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Ikot Ekpene", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Ini", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Mkpat Enin", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Itu", "state_id" => 2650, "senatorial_zone_id" => 7],
            ["title" => "Mbo", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Nsit Atai", "state_id" => 2650, "senatorial_zone_id" => 7],
            ["title" => "Nsit Ibom", "state_id" => 2650, "senatorial_zone_id" => 7],
            ["title" => "Nsit Ubium", "state_id" => 2650, "senatorial_zone_id" => 7],
            ["title" => "Obot Akara", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Okobo", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Onna", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Oron", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Udung Uko", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Ukanafun", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Oruk Anam", "state_id" => 2650, "senatorial_zone_id" => 8],
            ["title" => "Uruan", "state_id" => 2650, "senatorial_zone_id" => 7],
            ["title" => "Urue Offong/Oruko", "state_id" => 2650, "senatorial_zone_id" => 9],
            ["title" => "Uyo", "state_id" => 2650, "senatorial_zone_id" => 7],



            ["title" => "Aguata", "state_id" => 2651, "senatorial_zone_id" => 12],
            ["title" => "Anambra East", "state_id" => 2651, "senatorial_zone_id" => 10],
            ["title" => "Anaocha", "state_id" => 2651, "senatorial_zone_id" => 11],
            ["title" => "Awka North", "state_id" => 2651, "senatorial_zone_id" => 11],
            ["title" => "Anambra West", "state_id" => 2651, "senatorial_zone_id" => 10],
            ["title" => "Awka South", "state_id" => 2651, "senatorial_zone_id" => 11],
            ["title" => "Ayamelum", "state_id" => 2651, "senatorial_zone_id" => 10],
            ["title" => "Dunukofia", "state_id" => 2651, "senatorial_zone_id" => 11],
            ["title" => "Ekwusigo", "state_id" => 2651, "senatorial_zone_id" => 12],
            ["title" => "Idemili North", "state_id" => 2651, "senatorial_zone_id" => 11],
            ["title" => "Idemili South", "state_id" => 2651, "senatorial_zone_id" => 11],
            ["title" => "Ihiala", "state_id" => 2651, "senatorial_zone_id" => 12],
            ["title" => "Njikoka", "state_id" => 2651, "senatorial_zone_id" => 11],
            ["title" => "Nnewi North", "state_id" => 2651, "senatorial_zone_id" => 12],
            ["title" => "Nnewi South", "state_id" => 2651, "senatorial_zone_id" => 12],
            ["title" => "Ogbaru", "state_id" => 2651, "senatorial_zone_id" => 10],
            ["title" => "Onitsha North", "state_id" => 2651, "senatorial_zone_id" => 10],
            ["title" => "Onitsha South", "state_id" => 2651, "senatorial_zone_id" => 10],
            ["title" => "Orumba North", "state_id" => 2651, "senatorial_zone_id" => 12],
            ["title" => "Orumba South", "state_id" => 2651, "senatorial_zone_id" => 12],
            ["title" => "Oyi", "state_id" => 2651, "senatorial_zone_id" => 10],



            ["title" => "Abeokuta North", "state_id" => 2674, "senatorial_zone_id" => 79],
            ["title" => "Abeokuta South", "state_id" => 2674, "senatorial_zone_id" => 79],
            ["title" => "Ado Odo/Ota", "state_id" => 2674, "senatorial_zone_id" => 81],
            ["title" => "Egbado North", "state_id" => 2674, "senatorial_zone_id" => 81],
            ["title" => "Ewekoro", "state_id" => 2674, "senatorial_zone_id" => 79],
            ["title" => "Egbado South", "state_id" => 2674, "senatorial_zone_id" => 81],
            ["title" => "Ijebu North", "state_id" => 2674, "senatorial_zone_id" => 80],
            ["title" => "Ijebu East", "state_id" => 2674, "senatorial_zone_id" => 80],
            ["title" => "Ifo", "state_id" => 2674, "senatorial_zone_id" => 79],
            ["title" => "Ijebu Ode", "state_id" => 2674, "senatorial_zone_id" => 80],
            ["title" => "Ijebu North East", "state_id" => 2674, "senatorial_zone_id" => 80],
            ["title" => "Imeko Afon", "state_id" => 2674, "senatorial_zone_id" => 81],
            ["title" => "Ikenne", "state_id" => 2674, "senatorial_zone_id" => 80],
            ["title" => "Ipokia", "state_id" => 2674, "senatorial_zone_id" => 81],
            ["title" => "Odeda", "state_id" => 2674, "senatorial_zone_id" => 79],
            ["title" => "Obafemi Owode", "state_id" => 2674, "senatorial_zone_id" => 79],
            ["title" => "Odogbolu", "state_id" => 2674, "senatorial_zone_id" => 80],
            ["title" => "Remo North", "state_id" => 2674, "senatorial_zone_id" => 80],
            ["title" => "Ogun Waterside", "state_id" => 2674, "senatorial_zone_id" => 80],
            ["title" => "Shagamu", "state_id" => 2674, "senatorial_zone_id" => 80],



            ["title" => "Akoko North East", "state_id" => 2675, "senatorial_zone_id" => 82],
            ["title" => "Akoko North West", "state_id" => 2675, "senatorial_zone_id" => 82],
            ["title" => "Akoko South West", "state_id" => 2675, "senatorial_zone_id" => 82],
            ["title" => "Akoko South East", "state_id" => 2675, "senatorial_zone_id" => 82],
            ["title" => "Akure North", "state_id" => 2675, "senatorial_zone_id" => 83],
            ["title" => "Akure South", "state_id" => 2675, "senatorial_zone_id" => 83],
            ["title" => "Ese Odo", "state_id" => 2675, "senatorial_zone_id" => 84],
            ["title" => "Idanre", "state_id" => 2675, "senatorial_zone_id" => 83],
            ["title" => "Ifedore", "state_id" => 2675, "senatorial_zone_id" => 83],
            ["title" => "Ilaje", "state_id" => 2675, "senatorial_zone_id" => 84],
            ["title" => "Irele", "state_id" => 2675, "senatorial_zone_id" => 84],
            ["title" => "Ile Oluji/Okeigbo", "state_id" => 2675, "senatorial_zone_id" => 84],
            ["title" => "Odigbo", "state_id" => 2675, "senatorial_zone_id" => 84],
            ["title" => "Okitipupa", "state_id" => 2675, "senatorial_zone_id" => 84],
            ["title" => "Ondo West", "state_id" => 2675, "senatorial_zone_id" => 83],
            ["title" => "Ose", "state_id" => 2675, "senatorial_zone_id" => 82],
            ["title" => "Ondo East", "state_id" => 2675, "senatorial_zone_id" => 83],
            ["title" => "Owo", "state_id" => 2675, "senatorial_zone_id" => 82],



            ["title" => "Abua/Odual", "state_id" => 2679, "senatorial_zone_id" => 96],
            ["title" => "Ahoada East", "state_id" => 2679, "senatorial_zone_id" => 96],
            ["title" => "Ahoada West", "state_id" => 2679, "senatorial_zone_id" => 96],
            ["title" => "Andoni", "state_id" => 2679, "senatorial_zone_id" => 95],
            ["title" => "Akuku Toru", "state_id" => 2679, "senatorial_zone_id" => 96],
            ["title" => "Asari Toru", "state_id" => 2679, "senatorial_zone_id" => 96],
            ["title" => "Bonny", "state_id" => 2679, "senatorial_zone_id" => 96],
            ["title" => "Degema", "state_id" => 2679, "senatorial_zone_id" => 96],
            ["title" => "Emuoha", "state_id" => 2679, "senatorial_zone_id" => 94],
            ["title" => "Eleme", "state_id" => 2679, "senatorial_zone_id" => 95],
            ["title" => "Ikwerre", "state_id" => 2679, "senatorial_zone_id" => 94],
            ["title" => "Etche", "state_id" => 2679, "senatorial_zone_id" => 94],
            ["title" => "Gokana", "state_id" => 2679, "senatorial_zone_id" => 95],
            ["title" => "Khana", "state_id" => 2679, "senatorial_zone_id" => 95],
            ["title" => "Obio/Akpor", "state_id" => 2679, "senatorial_zone_id" => 94],
            ["title" => "Ogba/Egbema/Ndoni", "state_id" => 2679, "senatorial_zone_id" => 96],
            ["title" => "Ogu/Bolo", "state_id" => 2679, "senatorial_zone_id" => 94],
            ["title" => "Okrika", "state_id" => 2679, "senatorial_zone_id" => 94],
            ["title" => "Omuma", "state_id" => 2679, "senatorial_zone_id" => 94],
            ["title" => "Opobo/Nkoro", "state_id" => 2679, "senatorial_zone_id" => 95],
            ["title" => "Oyigbo", "state_id" => 2679, "senatorial_zone_id" => 95],
            ["title" => "Port Harcourt", "state_id" => 2679, "senatorial_zone_id" => 94],
            ["title" => "Tai", "state_id" => 2679, "senatorial_zone_id" => 95],


            ["title" => "Alkaleri", "state_id" => 2652, "senatorial_zone_id" => 13],
            ["title" => "Bauchi", "state_id" => 2652, "senatorial_zone_id" => 13],
            ["title" => "Bogoro", "state_id" => 2652, "senatorial_zone_id" => 13],
            ["title" => "Damban", "state_id" => 2652, "senatorial_zone_id" => 14],
            ["title" => "Darazo", "state_id" => 2652, "senatorial_zone_id" => 14],
            ["title" => "Dass", "state_id" => 2652, "senatorial_zone_id" => 13],
            ["title" => "Gamawa", "state_id" => 2652, "senatorial_zone_id" => 15],
            ["title" => "Ganjuwa", "state_id" => 2652, "senatorial_zone_id" => 14],
            ["title" => "Giade", "state_id" => 2652, "senatorial_zone_id" => 15],
            ["title" => "Itas/Gadau", "state_id" => 2652, "senatorial_zone_id" => 15],
            ["title" => "Jama'are", "state_id" => 2652, "senatorial_zone_id" => 15],
            ["title" => "Katagum", "state_id" => 2652, "senatorial_zone_id" => 15],
            ["title" => "Kirfi", "state_id" => 2652, "senatorial_zone_id" => 13],
            ["title" => "Misau", "state_id" => 2652, "senatorial_zone_id" => 14],
            ["title" => "Ningi", "state_id" => 2652, "senatorial_zone_id" => 14],
            ["title" => "Shira", "state_id" => 2652, "senatorial_zone_id" => 15],
            ["title" => "Tafawa Balewa", "state_id" => 2652, "senatorial_zone_id" => 13],
            ["title" => "Toro", "state_id" => 2652, "senatorial_zone_id" => 13],
            ["title" => "Warji", "state_id" => 2652, "senatorial_zone_id" => 14],
            ["title" => "Zaki", "state_id" => 2652, "senatorial_zone_id" => 15],



            ["title" => "Agatu", "state_id" => 2654, "senatorial_zone_id" => 21],
            ["title" => "Apa", "state_id" => 2654, "senatorial_zone_id" => 21],
            ["title" => "Ado", "state_id" => 2654, "senatorial_zone_id" => 21],
            ["title" => "Buruku", "state_id" => 2654, "senatorial_zone_id" => 20],
            ["title" => "Gboko", "state_id" => 2654, "senatorial_zone_id" => 20],
            ["title" => "Guma", "state_id" => 2654, "senatorial_zone_id" => 20],
            ["title" => "Gwer East", "state_id" => 2654, "senatorial_zone_id" => 20],
            ["title" => "Gwer West", "state_id" => 2654, "senatorial_zone_id" => 20],
            ["title" => "Katsina Ala", "state_id" => 2654, "senatorial_zone_id" => 19],
            ["title" => "Konshisha", "state_id" => 2654, "senatorial_zone_id" => 19],
            ["title" => "Kwande", "state_id" => 2654, "senatorial_zone_id" => 19],
            ["title" => "Logo", "state_id" => 2654, "senatorial_zone_id" => 19],
            ["title" => "Makurdi", "state_id" => 2654, "senatorial_zone_id" => 20],
            ["title" => "Obi", "state_id" => 2654, "senatorial_zone_id" => 21],
            ["title" => "Ogbadibo", "state_id" => 2654, "senatorial_zone_id" => 21],
            ["title" => "Ohimini", "state_id" => 2654, "senatorial_zone_id" => 21],
            ["title" => "Oju", "state_id" => 2654, "senatorial_zone_id" => 21],
            ["title" => "Okpokwu", "state_id" => 2654, "senatorial_zone_id" => 21],
            ["title" => "Otukpo", "state_id" => 2654, "senatorial_zone_id" => 21],
            ["title" => "Tarka", "state_id" => 2654, "senatorial_zone_id" => 20],
            ["title" => "Ukum", "state_id" => 2654, "senatorial_zone_id" => 19],
            ["title" => "Ushongo", "state_id" => 2654, "senatorial_zone_id" => 19],
            ["title" => "Vandeikya", "state_id" => 2654, "senatorial_zone_id" => 19],



            ["title" => "Abadam", "state_id" => 2655, "senatorial_zone_id" => 22],
            ["title" => "Askira/Uba", "state_id" => 2655, "senatorial_zone_id" => 24],
            ["title" => "Bama", "state_id" => 2655, "senatorial_zone_id" => 23],
            ["title" => "Bayo", "state_id" => 2655, "senatorial_zone_id" => 24],
            ["title" => "Biu", "state_id" => 2655, "senatorial_zone_id" => 24],
            ["title" => "Chibok", "state_id" => 2655, "senatorial_zone_id" => 24],
            ["title" => "Damboa", "state_id" => 2655, "senatorial_zone_id" => 24],
            ["title" => "Dikwa", "state_id" => 2655, "senatorial_zone_id" => 23],
            ["title" => "Guzamala", "state_id" => 2655, "senatorial_zone_id" => 22],
            ["title" => "Gubio", "state_id" => 2655, "senatorial_zone_id" => 22],
            ["title" => "Hawul", "state_id" => 2655, "senatorial_zone_id" => 24],
            ["title" => "Gwoza", "state_id" => 2655, "senatorial_zone_id" => 24],
            ["title" => "Jere", "state_id" => 2655, "senatorial_zone_id" => 23],
            ["title" => "Kaga", "state_id" => 2655, "senatorial_zone_id" => 23],
            ["title" => "Kala/Balge", "state_id" => 2655, "senatorial_zone_id" => 23],
            ["title" => "Konduga", "state_id" => 2655, "senatorial_zone_id" => 23],
            ["title" => "Kukawa", "state_id" => 2655, "senatorial_zone_id" => 22],
            ["title" => "Kwaya Kusar", "state_id" => 2655, "senatorial_zone_id" => 24],
            ["title" => "Mafa", "state_id" => 2655, "senatorial_zone_id" => 23],
            ["title" => "Magumeri", "state_id" => 2655, "senatorial_zone_id" => 22],
            ["title" => "Maiduguri", "state_id" => 2655, "senatorial_zone_id" => 23],
            ["title" => "Mobbar", "state_id" => 2655, "senatorial_zone_id" => 22],
            ["title" => "Marte", "state_id" => 2655, "senatorial_zone_id" => 22],
            ["title" => "Monguno", "state_id" => 2655, "senatorial_zone_id" => 22],
            ["title" => "Ngala", "state_id" => 2655, "senatorial_zone_id" => 23],
            ["title" => "Nganzai", "state_id" => 2655, "senatorial_zone_id" => 22],
            ["title" => "Shani", "state_id" => 2655, "senatorial_zone_id" => 24],


            ["title" => "Brass", "state_id" => 2653, "senatorial_zone_id" => 16],
            ["title" => "Ekeremor", "state_id" => 2653, "senatorial_zone_id" => 18],
            ["title" => "Kolokuma/Opokuma", "state_id" => 2653, "senatorial_zone_id" => 17],
            ["title" => "Nembe", "state_id" => 2653, "senatorial_zone_id" => 16],
            ["title" => "Ogbia", "state_id" => 2653, "senatorial_zone_id" => 16],
            ["title" => "Sagbama", "state_id" => 2653, "senatorial_zone_id" => 18],
            ["title" => "Southern Ijaw", "state_id" => 2653, "senatorial_zone_id" => 17],
            ["title" => "Yenagoa", "state_id" => 2653, "senatorial_zone_id" => 17],


            ["title" => "Abi", "state_id" => 2656, "senatorial_zone_id" => 26],
            ["title" => "Akamkpa", "state_id" => 2656, "senatorial_zone_id" => 27],
            ["title" => "Akpabuyo", "state_id" => 2656, "senatorial_zone_id" => 27],
            ["title" => "Bakassi", "state_id" => 2656, "senatorial_zone_id" => 27],
            ["title" => "Bekwarra", "state_id" => 2656, "senatorial_zone_id" => 25],
            ["title" => "Biase", "state_id" => 2656, "senatorial_zone_id" => 25],
            ["title" => "Boki", "state_id" => 2656, "senatorial_zone_id" => 26],
            ["title" => "Calabar Municipal", "state_id" => 2656, "senatorial_zone_id" => 27],
            ["title" => "Calabar South", "state_id" => 2656, "senatorial_zone_id" => 27],
            ["title" => "Etung", "state_id" => 2656, "senatorial_zone_id" => 26],
            ["title" => "Ikom", "state_id" => 2656, "senatorial_zone_id" => 26],
            ["title" => "Obanliku", "state_id" => 2656, "senatorial_zone_id" => 25],
            ["title" => "Obubra", "state_id" => 2656, "senatorial_zone_id" => 26],
            ["title" => "Obudu", "state_id" => 2656, "senatorial_zone_id" => 25],
            ["title" => "Odukpani", "state_id" => 2656, "senatorial_zone_id" => 27],
            ["title" => "Ogoja", "state_id" => 2656, "senatorial_zone_id" => 25],
            ["title" => "Yakuur", "state_id" => 2656, "senatorial_zone_id" => 26],
            ["title" => "Yala", "state_id" => 2656, "senatorial_zone_id" => 25],


            ["title" => "Aniocha North", "state_id" => 2657, "senatorial_zone_id" => 29],
            ["title" => "Aniocha South", "state_id" => 2657, "senatorial_zone_id" => 29],
            ["title" => "Bomadi", "state_id" => 2657, "senatorial_zone_id" => 30],
            ["title" => "Burutu", "state_id" => 2657, "senatorial_zone_id" => 30],
            ["title" => "Ethiope West", "state_id" => 2657, "senatorial_zone_id" => 28],
            ["title" => "Ethiope East", "state_id" => 2657, "senatorial_zone_id" => 28],
            ["title" => "Ika North East", "state_id" => 2657, "senatorial_zone_id" => 29],
            ["title" => "Ika South", "state_id" => 2657, "senatorial_zone_id" => 29],
            ["title" => "Isoko North", "state_id" => 2657, "senatorial_zone_id" => 30],
            ["title" => "Isoko South", "state_id" => 2657, "senatorial_zone_id" => 30],
            ["title" => "Ndokwa East", "state_id" => 2657, "senatorial_zone_id" => 29],
            ["title" => "Ndokwa West", "state_id" => 2657, "senatorial_zone_id" => 29],
            ["title" => "Okpe", "state_id" => 2657, "senatorial_zone_id" => 28],
            ["title" => "Oshimili North", "state_id" => 2657, "senatorial_zone_id" => 29],
            ["title" => "Oshimili South", "state_id" => 2657, "senatorial_zone_id" => 29],
            ["title" => "Patani", "state_id" => 2657, "senatorial_zone_id" => 30],
            ["title" => "Sapele", "state_id" => 2657, "senatorial_zone_id" => 28],
            ["title" => "Udu", "state_id" => 2657, "senatorial_zone_id" => 28],
            ["title" => "Ughelli North", "state_id" => 2657, "senatorial_zone_id" => 28],
            ["title" => "Ukwuani", "state_id" => 2657, "senatorial_zone_id" => 29],
            ["title" => "Ughelli South", "state_id" => 2657, "senatorial_zone_id" => 28],
            ["title" => "Uvwie", "state_id" => 2657, "senatorial_zone_id" => 28],
            ["title" => "Warri North", "state_id" => 2657, "senatorial_zone_id" => 30],
            ["title" => "Warri South", "state_id" => 2657, "senatorial_zone_id" => 30],
            ["title" => "Warri South West", "state_id" => 2657, "senatorial_zone_id" => 30],


            ["title" => "Abakaliki", "state_id" => 2658, "senatorial_zone_id" => 31],
            ["title" => "Afikpo North", "state_id" => 2658, "senatorial_zone_id" => 33],
            ["title" => "Ebonyi", "state_id" => 2658, "senatorial_zone_id" => 31],
            ["title" => "Afikpo South", "state_id" => 2658, "senatorial_zone_id" => 33],
            ["title" => "Ezza North", "state_id" => 2658, "senatorial_zone_id" => 32],
            ["title" => "Ikwo", "state_id" => 2658, "senatorial_zone_id" => 32],
            ["title" => "Ezza South", "state_id" => 2658, "senatorial_zone_id" => 32],
            ["title" => "Ivo", "state_id" => 2658, "senatorial_zone_id" => 33],
            ["title" => "Ishielu", "state_id" => 2658, "senatorial_zone_id" => 32],
            ["title" => "Izzi", "state_id" => 2658, "senatorial_zone_id" => 31],
            ["title" => "Ohaozara", "state_id" => 2658, "senatorial_zone_id" => 33],
            ["title" => "Ohaukwu", "state_id" => 2658, "senatorial_zone_id" => 31],
            ["title" => "Onicha", "state_id" => 2658, "senatorial_zone_id" => 33],



            ["title" => "Akoko Edo", "state_id" => 2659, "senatorial_zone_id" => 35],
            ["title" => "Egor", "state_id" => 2659, "senatorial_zone_id" => 36],
            ["title" => "Esan Central", "state_id" => 2659, "senatorial_zone_id" => 34],
            ["title" => "Esan North East", "state_id" => 2659, "senatorial_zone_id" => 34],
            ["title" => "Esan South East", "state_id" => 2659, "senatorial_zone_id" => 34],
            ["title" => "Esan West", "state_id" => 2659, "senatorial_zone_id" => 34],
            ["title" => "Etsako Central", "state_id" => 2659, "senatorial_zone_id" => 35],
            ["title" => "Etsako East", "state_id" => 2659, "senatorial_zone_id" => 35],
            ["title" => "Etsako West", "state_id" => 2659, "senatorial_zone_id" => 35],
            ["title" => "Igueben", "state_id" => 2659, "senatorial_zone_id" => 34],
            ["title" => "Ikpoba Okha", "state_id" => 2659, "senatorial_zone_id" => 36],
            ["title" => "Orhionmwon", "state_id" => 2659, "senatorial_zone_id" => 36],
            ["title" => "Oredo", "state_id" => 2659, "senatorial_zone_id" => 36],
            ["title" => "Ovia North East", "state_id" => 2659, "senatorial_zone_id" => 36],
            ["title" => "Ovia South West", "state_id" => 2659, "senatorial_zone_id" => 36],
            ["title" => "Owan East", "state_id" => 2659, "senatorial_zone_id" => 35],
            ["title" => "Owan West", "state_id" => 2659, "senatorial_zone_id" => 35],
            ["title" => "Uhunmwonde", "state_id" => 2659, "senatorial_zone_id" => 36],


            ["title" => "Ado Ekiti", "state_id" => 2660, "senatorial_zone_id" => 38],
            ["title" => "Efon", "state_id" => 2660, "senatorial_zone_id" => 38],
            ["title" => "Ekiti East", "state_id" => 2660, "senatorial_zone_id" => 39],
            ["title" => "Ekiti South West", "state_id" => 2660, "senatorial_zone_id" => 39],
            ["title" => "Ekiti West", "state_id" => 2660, "senatorial_zone_id" => 38],
            ["title" => "Emure", "state_id" => 2660, "senatorial_zone_id" => 39],
            ["title" => "Gbonyin", "state_id" => 2660, "senatorial_zone_id" => 39],
            ["title" => "Ido Osi", "state_id" => 2660, "senatorial_zone_id" => 37],
            ["title" => "Ijero", "state_id" => 2660, "senatorial_zone_id" => 38],
            ["title" => "Ikere", "state_id" => 2660, "senatorial_zone_id" => 39],
            ["title" => "Ilejemeje", "state_id" => 2660, "senatorial_zone_id" => 37],
            ["title" => "Irepodun/Ifelodun", "state_id" => 2660, "senatorial_zone_id" => 38],
            ["title" => "Ikole", "state_id" => 2660, "senatorial_zone_id" => 37],
            ["title" => "Ise/Orun", "state_id" => 2660, "senatorial_zone_id" => 39],
            ["title" => "Moba", "state_id" => 2660, "senatorial_zone_id" => 37],
            ["title" => "Oye", "state_id" => 2660, "senatorial_zone_id" => 37],


            ["title" => "Awgu", "state_id" => 2661, "senatorial_zone_id" => 41],
            ["title" => "Aninri", "state_id" => 2661, "senatorial_zone_id" => 41],
            ["title" => "Enugu East", "state_id" => 2661, "senatorial_zone_id" => 40],
            ["title" => "Enugu North", "state_id" => 2661, "senatorial_zone_id" => 40],
            ["title" => "Ezeagu", "state_id" => 2661, "senatorial_zone_id" => 41],
            ["title" => "Enugu South", "state_id" => 2661, "senatorial_zone_id" => 40],
            ["title" => "Igbo Etiti", "state_id" => 2661, "senatorial_zone_id" => 42],
            ["title" => "Igbo Eze North", "state_id" => 2661, "senatorial_zone_id" => 42],
            ["title" => "Igbo Eze South", "state_id" => 2661, "senatorial_zone_id" => 42],
            ["title" => "Isi Uzo", "state_id" => 2661, "senatorial_zone_id" => 40],
            ["title" => "Nkanu East", "state_id" => 2661, "senatorial_zone_id" => 40],
            ["title" => "Nkanu West", "state_id" => 2661, "senatorial_zone_id" => 40],
            ["title" => "Nsukka", "state_id" => 2661, "senatorial_zone_id" => 42],
            ["title" => "Udenu", "state_id" => 2661, "senatorial_zone_id" => 42],
            ["title" => "Oji River", "state_id" => 2661, "senatorial_zone_id" => 41],
            ["title" => "Uzo Uwani", "state_id" => 2661, "senatorial_zone_id" => 42],
            ["title" => "Udi", "state_id" => 2661, "senatorial_zone_id" => 41],


            ["title" => "Abaji", "state_id" => 2648, "senatorial_zone_id" => 109],
            ["title" => "Bwari", "state_id" => 2648, "senatorial_zone_id" => 109],
            ["title" => "Gwagwalada", "state_id" => 2648, "senatorial_zone_id" => 109],
            ["title" => "Kuje", "state_id" => 2648, "senatorial_zone_id" => 109],
            ["title" => "Kwali", "state_id" => 2648, "senatorial_zone_id" => 109],
            ["title" => "Municipal Area Council", "state_id" => 2648, "senatorial_zone_id" => 109],


            ["title" => "Akko", "state_id" => 2662, "senatorial_zone_id" => 43],
            ["title" => "Balanga", "state_id" => 2662, "senatorial_zone_id" => 44],
            ["title" => "Billiri", "state_id" => 2662, "senatorial_zone_id" => 44],
            ["title" => "Dukku", "state_id" => 2662, "senatorial_zone_id" => 45],
            ["title" => "Funakaye", "state_id" => 2662, "senatorial_zone_id" => 45],
            ["title" => "Gombe", "state_id" => 2662, "senatorial_zone_id" => 45],
            ["title" => "Kaltungo", "state_id" => 2662, "senatorial_zone_id" => 44],
            ["title" => "Kwami", "state_id" => 2662, "senatorial_zone_id" => 45],
            ["title" => "Nafada", "state_id" => 2662, "senatorial_zone_id" => 45],
            ["title" => "Shongom", "state_id" => 2662, "senatorial_zone_id" => 44],
            ["title" => "Yamaltu/Deba", "state_id" => 2662, "senatorial_zone_id" => 43],


            ["title" => "Auyo", "state_id" => 2664, "senatorial_zone_id" => 50],
            ["title" => "Babura", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Buji", "state_id" => 2664, "senatorial_zone_id" => 49],
            ["title" => "Biriniwa", "state_id" => 2664, "senatorial_zone_id" => 50],
            ["title" => "Birnin Kudu", "state_id" => 2664, "senatorial_zone_id" => 49],
            ["title" => "Dutse", "state_id" => 2664, "senatorial_zone_id" => 49],
            ["title" => "Gagarawa", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Garki", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Gumel", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Guri", "state_id" => 2664, "senatorial_zone_id" => 50],
            ["title" => "Gwaram", "state_id" => 2664, "senatorial_zone_id" => 49],
            ["title" => "Gwiwa", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Hadejia", "state_id" => 2664, "senatorial_zone_id" => 50],
            ["title" => "Jahun", "state_id" => 2664, "senatorial_zone_id" => 49],
            ["title" => "Kafin Hausa", "state_id" => 2664, "senatorial_zone_id" => 50],
            ["title" => "Kazaure", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Kiri Kasama", "state_id" => 2664, "senatorial_zone_id" => 50],
            ["title" => "Kiyawa", "state_id" => 2664, "senatorial_zone_id" => 49],
            ["title" => "Kaugama", "state_id" => 2664, "senatorial_zone_id" => 50],
            ["title" => "Maigatari", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Malam Madori", "state_id" => 2664, "senatorial_zone_id" => 50],
            ["title" => "Miga", "state_id" => 2664, "senatorial_zone_id" => 49],
            ["title" => "Sule Tankarkar", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Roni", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Ringim", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Yankwashi", "state_id" => 2664, "senatorial_zone_id" => 51],
            ["title" => "Taura", "state_id" => 2664, "senatorial_zone_id" => 51],

            ["title" => "Bakori", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Batagarawa", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Batsari", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Baure", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Bindawa", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Charanchi", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Danja", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Dandume", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Dan Musa", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Daura", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Dutsi", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Dutsin Ma", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Faskari", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Funtua", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Ingawa", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Jibia", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Kafur", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Kaita", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Kankara", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Kankia", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Katsina", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Kurfi", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Kusada", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Mai'Adua", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Malumfashi", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Mani", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Mashi", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Matazu", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Musawa", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Rimi", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Sabuwa", "state_id" => 2667, "senatorial_zone_id" => 59],
            ["title" => "Safana", "state_id" => 2667, "senatorial_zone_id" => 60],
            ["title" => "Sandamu", "state_id" => 2667, "senatorial_zone_id" => 58],
            ["title" => "Zango", "state_id" => 2667, "senatorial_zone_id" => 58],

            ["title" => "Asa", "state_id" => 2670, "senatorial_zone_id" =>68 ],
            ["title" => "Baruten", "state_id" => 2670, "senatorial_zone_id" => 67],
            ["title" => "Edu", "state_id" => 2670, "senatorial_zone_id" => 67],
            ["title" => "Ilorin East", "state_id" => 2670, "senatorial_zone_id" => 68],
            ["title" => "Ifelodun", "state_id" => 2670, "senatorial_zone_id" => 69],
            ["title" => "Ilorin South", "state_id" => 2670, "senatorial_zone_id" => 68],
            ["title" => "Ekiti Kwara State", "state_id" => 2670, "senatorial_zone_id" => 69],
            ["title" => "Ilorin West", "state_id" => 2670, "senatorial_zone_id" => 68],
            ["title" => "Irepodun", "state_id" => 2670, "senatorial_zone_id" => 69],
            ["title" => "Isin", "state_id" => 2670, "senatorial_zone_id" => 69],
            ["title" => "Kaiama", "state_id" => 2670, "senatorial_zone_id" => 67],
            ["title" => "Moro", "state_id" => 2670, "senatorial_zone_id" => 67],
            ["title" => "Offa", "state_id" => 2670, "senatorial_zone_id" => 68],
            ["title" => "Oke Ero", "state_id" => 2670, "senatorial_zone_id" => 69],
            ["title" => "Oyun", "state_id" => 2670, "senatorial_zone_id" => 69],
            ["title" => "Pategi", "state_id" => 2670, "senatorial_zone_id" => 67],


            ["title" => "Akwanga", "state_id" => 2672, "senatorial_zone_id" => 73],
            ["title" => "Awe", "state_id" => 2672, "senatorial_zone_id" => 75],
            ["title" => "Doma", "state_id" => 2672, "senatorial_zone_id" => 75],
            ["title" => "Karu", "state_id" => 2672, "senatorial_zone_id" => 74],
            ["title" => "Keana", "state_id" => 2672, "senatorial_zone_id" => 75],
            ["title" => "Keffi", "state_id" => 2672, "senatorial_zone_id" => 74],
            ["title" => "Lafia", "state_id" => 2672, "senatorial_zone_id" => 75],
            ["title" => "Kokona", "state_id" => 2672, "senatorial_zone_id" => 74],
            ["title" => "Nasarawa Egon", "state_id" => 2672, "senatorial_zone_id" => 73],
            ["title" => "Nasarawa", "state_id" => 2672, "senatorial_zone_id" => 74],
            ["title" => "Obi", "state_id" => 2672, "senatorial_zone_id" => 75],
            ["title" => "Toto", "state_id" => 2672, "senatorial_zone_id" => 74],
            ["title" => "Wamba", "state_id" => 2672, "senatorial_zone_id" => 73],


            ["title" => "Agaie", "state_id" => 2673, "senatorial_zone_id" => 78],
            ["title" => "Agwara", "state_id" => 2673, "senatorial_zone_id" => 77],
            ["title" => "Bida", "state_id" => 2673, "senatorial_zone_id" => 78],
            ["title" => "Borgu", "state_id" => 2673, "senatorial_zone_id" => 77],
            ["title" => "Bosso", "state_id" => 2673, "senatorial_zone_id" => 76],
            ["title" => "Chanchaga", "state_id" => 2673, "senatorial_zone_id" => 76],
            ["title" => "Edati", "state_id" => 2673, "senatorial_zone_id" => 78],
            ["title" => "Gbako", "state_id" => 2673, "senatorial_zone_id" => 78 ],
            ["title" => "Gurara", "state_id" => 2673, "senatorial_zone_id" => 76],
            ["title" => "Katcha", "state_id" => 2673, "senatorial_zone_id" => 78],
            ["title" => "Kontagora", "state_id" => 2673, "senatorial_zone_id" => 77],
            ["title" => "Lapai", "state_id" => 2673, "senatorial_zone_id" => 78],
            ["title" => "Lavun", "state_id" => 2673, "senatorial_zone_id" => 78],
            ["title" => "Mariga", "state_id" => 2673, "senatorial_zone_id" => 77],
            ["title" => "Magama", "state_id" => 2673, "senatorial_zone_id" => 77],
            ["title" => "Mokwa", "state_id" => 2673, "senatorial_zone_id" => 78],
            ["title" => "Mashegu", "state_id" => 2673, "senatorial_zone_id" => 77],
            ["title" => "Moya", "state_id" => 2673, "senatorial_zone_id" => 76],
            ["title" => "Paikoro", "state_id" => 2673, "senatorial_zone_id" =>76 ],
            ["title" => "Rafi", "state_id" => 2673, "senatorial_zone_id" => 76],
            ["title" => "Rijau", "state_id" => 2673, "senatorial_zone_id" => 77],
            ["title" => "Shiroro", "state_id" => 2673, "senatorial_zone_id" => 76],
            ["title" => "Suleja", "state_id" => 2673, "senatorial_zone_id" => 76],
            ["title" => "Tafa", "state_id" => 2673, "senatorial_zone_id" => 76],
            ["title" => "Wushishi", "state_id" => 2673, "senatorial_zone_id" => 77],


            ["title" => "Aba North", "state_id" => 2647, "senatorial_zone_id" => 3],
            ["title" => "Arochukwu", "state_id" => 2647, "senatorial_zone_id" => 1],
            ["title" => "Aba South", "state_id" => 2647, "senatorial_zone_id" => 3],
            ["title" => "Bende", "state_id" => 2647, "senatorial_zone_id" => 1],
            ["title" => "Isiala Ngwa North", "state_id" => 2647, "senatorial_zone_id" => 2],
            ["title" => "Ikwuano", "state_id" => 2647, "senatorial_zone_id" => 2],
            ["title" => "Isiala Ngwa South", "state_id" => 2647, "senatorial_zone_id" => 2],
            ["title" => "Isuikwuato", "state_id" => 2647, "senatorial_zone_id" => 1],
            ["title" => "Obi Ngwa", "state_id" => 2647, "senatorial_zone_id" => 3],
            ["title" => "Ohafia", "state_id" => 2647, "senatorial_zone_id" => 1],
            ["title" => "Osisioma", "state_id" => 2647, "senatorial_zone_id" => 3],
            ["title" => "Ugwunagbo", "state_id" => 2647, "senatorial_zone_id" => 3],
            ["title" => "Ukwa East", "state_id" => 2647, "senatorial_zone_id" => 3],
            ["title" => "Ukwa West", "state_id" => 2647, "senatorial_zone_id" => 3],
            ["title" => "Umuahia North", "state_id" => 2647, "senatorial_zone_id" => 2],
            ["title" => "Umuahia South", "state_id" => 2647, "senatorial_zone_id" => 2],
            ["title" => "Umu Nneochi", "state_id" => 2647, "senatorial_zone_id" => 1],

            
            ["title" => "Afijio", "state_id" => 2677, "senatorial_zone_id" => 88],
            ["title" => "Akinyele", "state_id" => 2677, "senatorial_zone_id" => 88],
            ["title" => "Atiba", "state_id" => 2677, "senatorial_zone_id" => 88],
            ["title" => "Atigbo", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Egbeda", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Ibadan North", "state_id" => 2677, "senatorial_zone_id" => 90],
            ["title" => "Ibadan North East", "state_id" => 2677, "senatorial_zone_id" => 90],
            ["title" => "Ibadan North West", "state_id" => 2677, "senatorial_zone_id" => 90],
            ["title" => "Ibadan South East", "state_id" => 2677, "senatorial_zone_id" => 90],
            ["title" => "Ibarapa Central", "state_id" => 2677, "senatorial_zone_id" => 90],
            ["title" => "Ibadan South West", "state_id" => 2677, "senatorial_zone_id" => 90],
            ["title" => "Ibarapa East", "state_id" => 2677, "senatorial_zone_id" => 90],
            ["title" => "Ido", "state_id" => 2677, "senatorial_zone_id" => 90],
            ["title" => "Ibarapa North", "state_id" => 2677, "senatorial_zone_id" => 90],
            ["title" => "Irepo", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Iseyin", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Itesiwaju", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Iwajowa", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Kajola", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Lagelu", "state_id" => 2677, "senatorial_zone_id" => 88],
            ["title" => "Ogbomosho North", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Ogbomosho South", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Ogo Oluwa", "state_id" => 2677, "senatorial_zone_id" => 88],
            ["title" => "Olorunsogo", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Oluyole", "state_id" => 2677, "senatorial_zone_id" => 88],
            ["title" => "Ona Ara", "state_id" => 2677, "senatorial_zone_id" => 88],
            ["title" => "Orelope", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Orire", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Oyo West", "state_id" => 2677, "senatorial_zone_id" => 88],
            ["title" => "Oyo East", "state_id" => 2677, "senatorial_zone_id" => 88],
            ["title" => "Saki East", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Saki West", "state_id" => 2677, "senatorial_zone_id" => 89],
            ["title" => "Surulere Oyo State", "state_id" => 2677, "senatorial_zone_id" => 88],


            ["title" => "Aboh Mbaise", "state_id" => 2663, "senatorial_zone_id" => 46],
            ["title" => "Ahiazu Mbaise", "state_id" => 2663, "senatorial_zone_id" => 46],
            ["title" => "Ehime Mbano", "state_id" => 2663, "senatorial_zone_id" => 48],
            ["title" => "Ezinihitte", "state_id" => 2663, "senatorial_zone_id" => 46],
            ["title" => "Ideato North", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Ideato South", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Ihite/Uboma", "state_id" => 2663, "senatorial_zone_id" => 48],
            ["title" => "Ikeduru", "state_id" => 2663, "senatorial_zone_id" => 46],
            ["title" => "Isiala Mbano", "state_id" => 2663, "senatorial_zone_id" => 48],
            ["title" => "Mbaitoli", "state_id" => 2663, "senatorial_zone_id" => 46],
            ["title" => "Isu", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Ngor Okpala", "state_id" => 2663, "senatorial_zone_id" => 46],
            ["title" => "Njaba", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Nkwere", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Nwangele", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Obowo", "state_id" => 2663, "senatorial_zone_id" => 48],
            ["title" => "Oguta", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Ohaji/Egbema", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Okigwe", "state_id" => 2663, "senatorial_zone_id" => 48],
            ["title" => "Orlu", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Orsu", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Oru East", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Oru West", "state_id" => 2663, "senatorial_zone_id" => 47],
            ["title" => "Owerri Municipal", "state_id" => 2663, "senatorial_zone_id" => 46],
            ["title" => "Owerri North", "state_id" => 2663, "senatorial_zone_id" => 46],
            ["title" => "Owerri West", "state_id" => 2663, "senatorial_zone_id" => 46],
            ["title" => "Onuimo", "state_id" => 2663, "senatorial_zone_id" => 48],
            


            ["title" => "Birnin Gwari", "state_id" => 2665, "senatorial_zone_id" => 53],
            ["title" => "Chikun", "state_id" => 2665, "senatorial_zone_id" => 53],
            ["title" => "Giwa", "state_id" => 2665, "senatorial_zone_id" => 53],
            ["title" => "Ikara", "state_id" => 2665, "senatorial_zone_id" => 52],
            ["title" => "Igabi", "state_id" => 2665, "senatorial_zone_id" => 53],
            ["title" => "Jaba", "state_id" => 2665, "senatorial_zone_id" => 54],
            ["title" => "Jema'a", "state_id" => 2665, "senatorial_zone_id" => 54],
            ["title" => "Kachia", "state_id" => 2665, "senatorial_zone_id" => 54],
            ["title" => "Kaduna North", "state_id" => 2665, "senatorial_zone_id" => 53],
            ["title" => "Kaduna South", "state_id" => 2665, "senatorial_zone_id" => 53],
            ["title" => "Kagarko", "state_id" => 2665, "senatorial_zone_id" => 54],
            ["title" => "Kajuru", "state_id" => 2665, "senatorial_zone_id" => 53],
            ["title" => "Kaura", "state_id" => 2665, "senatorial_zone_id" => 54],
            ["title" => "Kauru", "state_id" => 2665, "senatorial_zone_id" => 54],
            ["title" => "Kubau", "state_id" => 2665, "senatorial_zone_id" => 52],
            ["title" => "Kudan", "state_id" => 2665, "senatorial_zone_id" => 52],
            ["title" => "Lere", "state_id" => 2665, "senatorial_zone_id" => 52],
            ["title" => "Makarfi", "state_id" => 2665, "senatorial_zone_id" => 52],
            ["title" => "Sabon Gari", "state_id" => 2665, "senatorial_zone_id" => 52],
            ["title" => "Sanga", "state_id" => 2665, "senatorial_zone_id" => 54],
            ["title" => "Soba", "state_id" => 2665, "senatorial_zone_id" => 52],
            ["title" => "Zangon Kataf", "state_id" => 2665, "senatorial_zone_id" => 54],
            ["title" => "Zaria", "state_id" => 2665, "senatorial_zone_id" => 52],


            ["title" => "Aleiro", "state_id" => 2668, "senatorial_zone_id" => 62],
            ["title" => "Argungu", "state_id" => 2668, "senatorial_zone_id" => 61],
            ["title" => "Arewa Dandi", "state_id" => 2668, "senatorial_zone_id" => 61],
            ["title" => "Augie", "state_id" => 2668, "senatorial_zone_id" => 61],
            ["title" => "Bagudo", "state_id" => 2668, "senatorial_zone_id" => 61],
            ["title" => "Birnin Kebbi", "state_id" => 2668, "senatorial_zone_id" => 62],
            ["title" => "Bunza", "state_id" => 2668, "senatorial_zone_id" => 62],
            ["title" => "Dandi", "state_id" => 2668, "senatorial_zone_id" => 61],
            ["title" => "Fakai", "state_id" => 2668, "senatorial_zone_id" => 63],
            ["title" => "Gwandu", "state_id" => 2668, "senatorial_zone_id" => 62],
            ["title" => "Jega", "state_id" => 2668, "senatorial_zone_id" => 61],
            ["title" => "Kalgo", "state_id" => 2668, "senatorial_zone_id" => 62],
            ["title" => "Koko Besse", "state_id" => 2668, "senatorial_zone_id" => 62],
            ["title" => "Maiyama", "state_id" => 2668, "senatorial_zone_id" => 62],
            ["title" => "Ngaski", "state_id" => 2668, "senatorial_zone_id" => 63],
            ["title" => "Shanga", "state_id" => 2668, "senatorial_zone_id" => 63],
            ["title" => "Suru", "state_id" => 2668, "senatorial_zone_id" => 61],
            ["title" => "Sakaba", "state_id" => 2668, "senatorial_zone_id" => 63],
            ["title" => "Wasagu/Danko", "state_id" => 2668, "senatorial_zone_id" => 63],
            ["title" => "Yauri", "state_id" => 2668, "senatorial_zone_id" => 63],
            ["title" => "Zuru", "state_id" => 2668, "senatorial_zone_id" => 63],


            ["title" => "Ajingi", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Albasu", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Bagwai", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Bebeji", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Bichi", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Bunkure", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Dala", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Danbatta", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Dawakin Kudu", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Dawakin Tofa", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Doguwa", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Fagge", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Gabasawa", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Garko", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Garun Mallam", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Gezawa", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Gaya", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Gwale", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Gwarzo", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Kabo", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Kano Municipal", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Karaye", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Kibiya", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Kiru", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Kumbotso", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Kunchi", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Kura", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Madobi", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Makoda", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Minjibir", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Nassarawa", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Rano", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Rimi Gado", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Rogo", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Shanono", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Takai", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Sumaila", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Tarauni", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Tofa", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Tsanyawa", "state_id" => 2666, "senatorial_zone_id" => 56],
            ["title" => "Tudun Wada", "state_id" => 2666, "senatorial_zone_id" => 57],
            ["title" => "Ungogo", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Warawa", "state_id" => 2666, "senatorial_zone_id" => 55],
            ["title" => "Wudil", "state_id" => 2666, "senatorial_zone_id" => 57],


            ["title" => "Ajaokuta", "state_id" => 2669, "senatorial_zone_id" => 64],
            ["title" => "Adavi", "state_id" => 2669, "senatorial_zone_id" => 64],
            ["title" => "Ankpa", "state_id" => 2669, "senatorial_zone_id" => 65],
            ["title" => "Bassa", "state_id" => 2669, "senatorial_zone_id" => 65],
            ["title" => "Dekina", "state_id" => 2669, "senatorial_zone_id" => 65],
            ["title" => "Ibaji", "state_id" => 2669, "senatorial_zone_id" => 65],
            ["title" => "Idah", "state_id" => 2669, "senatorial_zone_id" => 65],
            ["title" => "Igalamela Odolu", "state_id" => 2669, "senatorial_zone_id" => 65],
            ["title" => "Ijumu", "state_id" => 2669, "senatorial_zone_id" => 66],
            ["title" => "Kogi", "state_id" => 2669, "senatorial_zone_id" => 64],
            ["title" => "Kabba/Bunu", "state_id" => 2669, "senatorial_zone_id" => 66],
            ["title" => "Lokoja", "state_id" => 2669, "senatorial_zone_id" => 66],
            ["title" => "Ofu", "state_id" => 2669, "senatorial_zone_id" => 65],
            ["title" => "Mopa Muro", "state_id" => 2669, "senatorial_zone_id" => 66],
            ["title" => "Ogori/Magongo", "state_id" => 2669, "senatorial_zone_id" => 64],
            ["title" => "Okehi", "state_id" => 2669, "senatorial_zone_id" => 64],
            ["title" => "Okene", "state_id" => 2669, "senatorial_zone_id" => 64],
            ["title" => "Olamaboro", "state_id" => 2669, "senatorial_zone_id" => 65],
            ["title" => "Omala", "state_id" => 2669, "senatorial_zone_id" => 65],
            ["title" => "Yagba East", "state_id" => 2669, "senatorial_zone_id" => 66],
            ["title" => "Yagba West", "state_id" => 2669, "senatorial_zone_id" => 66],



            ["title" => "Aiyedire", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Atakunmosa West", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Atakunmosa East", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Aiyedaade", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Bolowaduro", "state_id" => 2676, "senatorial_zone_id" => 85],
            ["title" => "Boripe", "state_id" => 2676, "senatorial_zone_id" => 85],
            ["title" => "Ife East", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Ede South", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Ife North", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Ede North", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Ife South", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Ejigbo", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Ife Central", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Ifedayo", "state_id" => 2676, "senatorial_zone_id" => 85],
            ["title" => "Egbedore", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Ila", "state_id" => 2676, "senatorial_zone_id" => 85],
            ["title" => "Ifelodun", "state_id" => 2676, "senatorial_zone_id" => 85],
            ["title" => "Ilesa East", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Ilesa West", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Irepodun", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Irewole", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Isokan", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Iwo", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Obokun", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Odo Otin", "state_id" => 2676, "senatorial_zone_id" => 85],
            ["title" => "Ola Oluwa", "state_id" => 2676, "senatorial_zone_id" => 87],
            ["title" => "Olorunda", "state_id" => 2676, "senatorial_zone_id" => 85],
            ["title" => "Oriade", "state_id" => 2676, "senatorial_zone_id" => 86],
            ["title" => "Orolu", "state_id" => 2676, "senatorial_zone_id" => 85],
            ["title" => "Osogbo", "state_id" => 2676, "senatorial_zone_id" => 85],



            ["title" => "Gudu", "state_id" => 2680, "senatorial_zone_id" => 98],
            ["title" => "Gwadabawa", "state_id" => 2680, "senatorial_zone_id" => 97],
            ["title" => "Illela", "state_id" => 2680, "senatorial_zone_id" => 97],
            ["title" => "Isa", "state_id" => 2680, "senatorial_zone_id" => 97],
            ["title" => "Kebbe", "state_id" => 2680, "senatorial_zone_id" => 99],
            ["title" => "Kware", "state_id" => 2680, "senatorial_zone_id" => 98],
            ["title" => "Rabah", "state_id" => 2680, "senatorial_zone_id" => 97],
            ["title" => "Sabon Birni", "state_id" => 2680, "senatorial_zone_id" => 97],
            ["title" => "Shagari", "state_id" => 2680, "senatorial_zone_id" => 99],
            ["title" => "Silame", "state_id" => 2680, "senatorial_zone_id" => 98],
            ["title" => "Sokoto North", "state_id" => 2680, "senatorial_zone_id" => 98],
            ["title" => "Sokoto South", "state_id" => 2680, "senatorial_zone_id" => 99],
            ["title" => "Tambuwal", "state_id" => 2680, "senatorial_zone_id" => 99],
            ["title" => "Tangaza", "state_id" => 2680, "senatorial_zone_id" => 98],
            ["title" => "Tureta", "state_id" => 2680, "senatorial_zone_id" => 99],
            ["title" => "Wamako", "state_id" => 2680, "senatorial_zone_id" => 98],
            ["title" => "Wurno", "state_id" => 2680, "senatorial_zone_id" => 97],
            ["title" => "Yabo", "state_id" => 2680, "senatorial_zone_id" => 99],
            ["title" => "Binji", "state_id" => 2680, "senatorial_zone_id" => 98],
            ["title" => "Bodinga", "state_id" => 2680, "senatorial_zone_id" => 99],
            ["title" => "Dange Shuni", "state_id" => 2680, "senatorial_zone_id" => 99],
            ["title" => "Goronyo", "state_id" => 2680, "senatorial_zone_id" => 97],
            ["title" => "Gada", "state_id" => 2680, "senatorial_zone_id" => 97],


            ["title" => "Bokkos", "state_id" => 2678, "senatorial_zone_id" => 92],
            ["title" => "Barkin Ladi", "state_id" => 2678, "senatorial_zone_id" => 93],
            ["title" => "Bassa", "state_id" => 2678, "senatorial_zone_id" => 93],
            ["title" => "Jos East", "state_id" => 2678, "senatorial_zone_id" => 93],
            ["title" => "Jos North", "state_id" => 2678, "senatorial_zone_id" => 93],
            ["title" => "Jos South", "state_id" => 2678, "senatorial_zone_id" => 93],
            ["title" => "Kanam", "state_id" => 2678, "senatorial_zone_id" => 92],
            ["title" => "Kanke", "state_id" => 2678, "senatorial_zone_id" => 92],
            ["title" => "Lantang South", "state_id" => 2678, "senatorial_zone_id" => 91],
            ["title" => "Lantang North", "state_id" => 2678, "senatorial_zone_id" => 91],
            ["title" => "Mangu", "state_id" => 2678, "senatorial_zone_id" => 92],
            ["title" => "Mikang", "state_id" => 2678, "senatorial_zone_id" => 91],
            ["title" => "Pankshin", "state_id" => 2678, "senatorial_zone_id" => 92],
            ["title" => "Qua'an Pan", "state_id" => 2678, "senatorial_zone_id" => 91],
            ["title" => "Riyom", "state_id" => 2678, "senatorial_zone_id" => 93],
            ["title" => "Shendam", "state_id" => 2678, "senatorial_zone_id" => 91],
            ["title" => "Wase", "state_id" => 2678, "senatorial_zone_id" => 91],


            ["title" => "Ardo Kola", "state_id" => 2681, "senatorial_zone_id" => 102],
            ["title" => "Bali", "state_id" => 2681, "senatorial_zone_id" => 101],
            ["title" => "Donga", "state_id" => 2681, "senatorial_zone_id" => 100],
            ["title" => "Gashaka", "state_id" => 2681, "senatorial_zone_id" => 101],
            ["title" => "Gassol", "state_id" => 2681, "senatorial_zone_id" => 101],
            ["title" => "Ibi", "state_id" => 2681, "senatorial_zone_id" => 100],
            ["title" => "Jalingo", "state_id" => 2681, "senatorial_zone_id" => 102],
            ["title" => "Karim Lamido", "state_id" => 2681, "senatorial_zone_id" => 102],
            ["title" => "Kurmi", "state_id" => 2681, "senatorial_zone_id" => 101],
            ["title" => "Lau", "state_id" => 2681, "senatorial_zone_id" => 102],
            ["title" => "Sardauna", "state_id" => 2681, "senatorial_zone_id" => 101],
            ["title" => "Takum", "state_id" => 2681, "senatorial_zone_id" => 100],
            ["title" => "Ussa", "state_id" => 2681, "senatorial_zone_id" => 100],
            ["title" => "Wukari", "state_id" => 2681, "senatorial_zone_id" => 100],
            ["title" => "Yorro", "state_id" => 2681, "senatorial_zone_id" => 102],
            ["title" => "Zing", "state_id" => 2681, "senatorial_zone_id" => 102],


            ["title" => "Bade", "state_id" => 2682, "senatorial_zone_id" => 104],
            ["title" => "Bursari", "state_id" => 2682, "senatorial_zone_id" => 103],
            ["title" => "Damaturu", "state_id" => 2682, "senatorial_zone_id" => 105],
            ["title" => "Fika", "state_id" => 2682, "senatorial_zone_id" => 105],
            ["title" => "Fune", "state_id" => 2682, "senatorial_zone_id" => 105],
            ["title" => "Geidam", "state_id" => 2682, "senatorial_zone_id" => 103],
            ["title" => "Gujba", "state_id" => 2682, "senatorial_zone_id" => 103],
            ["title" => "Gulani", "state_id" => 2682, "senatorial_zone_id" => 103],
            ["title" => "Jakusko", "state_id" => 2682, "senatorial_zone_id" => 104],
            ["title" => "Karasuwa", "state_id" => 2682, "senatorial_zone_id" => 104],
            ["title" => "Machina", "state_id" => 2682, "senatorial_zone_id" => 104],
            ["title" => "Nangere", "state_id" => 2682, "senatorial_zone_id" => 105],
            ["title" => "Nguru", "state_id" => 2682, "senatorial_zone_id" => 104],
            ["title" => "Potiskum", "state_id" => 2682, "senatorial_zone_id" => 105],
            ["title" => "Tarmuwa", "state_id" => 2682, "senatorial_zone_id" => 103],
            ["title" => "Yunusari", "state_id" => 2682, "senatorial_zone_id" => 103],
            ["title" => "Yusufari", "state_id" => 2682, "senatorial_zone_id" => 104],


            ["title" => "Anka", "state_id" => 2683, "senatorial_zone_id" => 108],
            ["title" => "Birnin Magaji/Kiyaw", "state_id" => 2683, "senatorial_zone_id" => 106],
            ["title" => "Bakura", "state_id" => 2683, "senatorial_zone_id" => 108],
            ["title" => "Bukkuyum", "state_id" => 2683, "senatorial_zone_id" => 108],
            ["title" => "Bungudu", "state_id" => 2683, "senatorial_zone_id" => 107],
            ["title" => "Gummi", "state_id" => 2683, "senatorial_zone_id" => 108],
            ["title" => "Gusau", "state_id" => 2683, "senatorial_zone_id" => 107],
            ["title" => "Kaura Namoda", "state_id" => 2683, "senatorial_zone_id" => 106],
            ["title" => "Maradun", "state_id" => 2683, "senatorial_zone_id" => 108],
            ["title" => "Shinkafi", "state_id" => 2683, "senatorial_zone_id" => 106],
            ["title" => "Maru", "state_id" => 2683, "senatorial_zone_id" => 107],
            ["title" => "Talata Mafara", "state_id" => 2683, "senatorial_zone_id" => 106],
            ["title" => "Tsafe", "state_id" => 2683, "senatorial_zone_id" => 107],
            ["title" => "Zurmi", "state_id" => 2683, "senatorial_zone_id" => 106],


            ["title" => "Agege", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Ajeromi Ifelodun", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Alimosho", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Amuwo Odofin", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Badagry", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Apapa", "state_id" => 2671, "senatorial_zone_id" => 70],
            ["title" => "Epe", "state_id" => 2671, "senatorial_zone_id" => 71],
            ["title" => "Eti Osa", "state_id" => 2671, "senatorial_zone_id" => 70],
            ["title" => "Ibeju Lekki", "state_id" => 2671, "senatorial_zone_id" => 71],
            ["title" => "Ifako Ijaiye", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Ikeja", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Ikorodu", "state_id" => 2671, "senatorial_zone_id" => 71],
            ["title" => "Kosofe", "state_id" => 2671, "senatorial_zone_id" => 71],
            ["title" => "Lagos Island", "state_id" => 2671, "senatorial_zone_id" => 70],
            ["title" => "Mushin", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Lagos Mainland", "state_id" => 2671, "senatorial_zone_id" => 70],
            ["title" => "Ojo", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Oshodi Isolo", "state_id" => 2671, "senatorial_zone_id" => 72],
            ["title" => "Shomolu", "state_id" => 2671, "senatorial_zone_id" => 71],
            ["title" => "Surulere Lagos State", "state_id" => 2671, "senatorial_zone_id" => 70],

        ];

        DB::table('local_govt_areas')->insert($local_govt_areas);
    }
}
